import {
  ThemeDefinition,
  ThemeId,
  ThemePreference,
} from "./types";

export const THEME_DEFINITIONS: Record<ThemeId, ThemeDefinition> = {
  // ─── DARK THEMES (7) ───────────────────────────────────────────────────────
  "dark-modern": {
    id: "dark-modern",
    name: "Dark Modern",
    category: "dark",
    description: "Default modern VS Code dark theme with refined contrast and subtle surfaces.",
    colors: {
      background: "#181818",
      foreground: "#CCCCCC",
      card: "#202020",
      cardForeground: "#CCCCCC",
      popover: "#222222",
      popoverForeground: "#FFFFFF",
      primary: "#0078D4",
      primaryForeground: "#FFFFFF",
      secondary: "#2A2A2A",
      secondaryForeground: "#FFFFFF",
      muted: "#2A2A2A",
      mutedForeground: "#9D9D9D",
      accent: "#2A2A2A",
      accentForeground: "#FFFFFF",
      border: "#2B2B2B",
      input: "#313131",
      ring: "#0078D4",
      success: "#2EA043",
      warning: "#BB8009",
      destructive: "#F85149",
      info: "#4DAAFC",
      sidebar: "#181818",
      sidebarForeground: "#CCCCCC",
      sidebarPrimary: "#0078D4",
      sidebarPrimaryForeground: "#FFFFFF",
      sidebarAccent: "#2A2A2A",
      sidebarAccentForeground: "#FFFFFF",
      sidebarBorder: "#2B2B2B",
      sidebarRing: "#0078D4",
    },
    monaco: {
      base: "vs-dark",
      rules: [
        { token: "comment", foreground: "6A9955", fontStyle: "italic" },
        { token: "keyword", foreground: "569CD6" },
        { token: "string", foreground: "CE9178" },
        { token: "number", foreground: "B5CEA8" },
        { token: "type", foreground: "4EC9B0" },
        { token: "class", foreground: "4EC9B0" },
        { token: "function", foreground: "DCDCAA" },
        { token: "variable", foreground: "9CDCFE" },
        { token: "delimiter", foreground: "CCCCCC" },
      ],
      colors: {
        "editor.background": "#1F1F1F",
        "editor.foreground": "#CCCCCC",
        "editorCursor.foreground": "#0078D4",
        "editor.lineHighlightBackground": "#282828",
        "editorLineNumber.foreground": "#6E7681",
        "editorLineNumber.activeForeground": "#CCCCCC",
        "editor.selectionBackground": "#3A3D41",
        "editor.inactiveSelectionBackground": "#2A2D30",
        "editorIndentGuide.background": "#313131",
        "editorIndentGuide.activeBackground": "#4B4B4B",
        "editorSuggestWidget.background": "#222222",
        "editorSuggestWidget.border": "#2B2B2B",
        "editorSuggestWidget.foreground": "#CCCCCC",
        "editorSuggestWidget.selectedBackground": "#3A3D41",
        "editorSuggestWidget.highlightForeground": "#0078D4",
        "editorSuggestWidget.focusHighlightForeground": "#4DAAFC",
      },
    },
  },

  "dark-plus": {
    id: "dark-plus",
    name: "Dark+",
    category: "dark",
    description: "Classic VS Code Dark+ theme with rich syntax colors.",
    colors: {
      background: "#1E1E1E",
      foreground: "#D4D4D4",
      card: "#252526",
      cardForeground: "#D4D4D4",
      popover: "#252526",
      popoverForeground: "#D4D4D4",
      primary: "#007ACC",
      primaryForeground: "#FFFFFF",
      secondary: "#2D2D2D",
      secondaryForeground: "#D4D4D4",
      muted: "#2D2D2D",
      mutedForeground: "#858585",
      accent: "#2D2D2D",
      accentForeground: "#FFFFFF",
      border: "#3E3E42",
      input: "#3C3C3C",
      ring: "#007ACC",
      success: "#89D185",
      warning: "#CCA700",
      destructive: "#F44747",
      info: "#3794FF",
      sidebar: "#252526",
      sidebarForeground: "#D4D4D4",
      sidebarPrimary: "#007ACC",
      sidebarPrimaryForeground: "#FFFFFF",
      sidebarAccent: "#37373D",
      sidebarAccentForeground: "#FFFFFF",
      sidebarBorder: "#3E3E42",
      sidebarRing: "#007ACC",
    },
    monaco: {
      base: "vs-dark",
      rules: [
        { token: "comment", foreground: "6A9955", fontStyle: "italic" },
        { token: "keyword", foreground: "C586C0" },
        { token: "string", foreground: "CE9178" },
        { token: "number", foreground: "B5CEA8" },
        { token: "type", foreground: "4EC9B0" },
        { token: "class", foreground: "4EC9B0" },
        { token: "function", foreground: "DCDCAA" },
        { token: "variable", foreground: "9CDCFE" },
        { token: "delimiter", foreground: "D4D4D4" },
      ],
      colors: {
        "editor.background": "#1E1E1E",
        "editor.foreground": "#D4D4D4",
        "editorCursor.foreground": "#AEAFAD",
        "editor.lineHighlightBackground": "#282828",
        "editorLineNumber.foreground": "#858585",
        "editorLineNumber.activeForeground": "#C6C6C6",
        "editor.selectionBackground": "#264F78",
        "editor.inactiveSelectionBackground": "#3A3D41",
        "editorIndentGuide.background": "#404040",
        "editorIndentGuide.activeBackground": "#707070",
        "editorSuggestWidget.background": "#252526",
        "editorSuggestWidget.border": "#3E3E42",
        "editorSuggestWidget.foreground": "#D4D4D4",
        "editorSuggestWidget.selectedBackground": "#04395E",
        "editorSuggestWidget.highlightForeground": "#007ACC",
        "editorSuggestWidget.focusHighlightForeground": "#3794FF",
      },
    },
  },

  "vs-dark": {
    id: "vs-dark",
    name: "Visual Studio Dark",
    category: "dark",
    description: "Traditional Visual Studio IDE dark theme.",
    colors: {
      background: "#1E1E1E",
      foreground: "#CCCCCC",
      card: "#252526",
      cardForeground: "#CCCCCC",
      popover: "#252526",
      popoverForeground: "#CCCCCC",
      primary: "#0078D4",
      primaryForeground: "#FFFFFF",
      secondary: "#2D2D2D",
      secondaryForeground: "#FFFFFF",
      muted: "#2D2D2D",
      mutedForeground: "#A6A6A6",
      accent: "#37373D",
      accentForeground: "#FFFFFF",
      border: "#454545",
      input: "#3C3C3C",
      ring: "#0078D4",
      success: "#369432",
      warning: "#CCA700",
      destructive: "#F48771",
      info: "#007ACC",
      sidebar: "#252526",
      sidebarForeground: "#CCCCCC",
      sidebarPrimary: "#0078D4",
      sidebarPrimaryForeground: "#FFFFFF",
      sidebarAccent: "#37373D",
      sidebarAccentForeground: "#FFFFFF",
      sidebarBorder: "#454545",
      sidebarRing: "#0078D4",
    },
    monaco: {
      base: "vs-dark",
      rules: [
        { token: "comment", foreground: "57A64A", fontStyle: "italic" },
        { token: "keyword", foreground: "569CD6" },
        { token: "string", foreground: "D69D85" },
        { token: "number", foreground: "B5CEA8" },
        { token: "type", foreground: "4EC9B0" },
        { token: "class", foreground: "4EC9B0" },
        { token: "function", foreground: "DCDCAA" },
        { token: "variable", foreground: "BD63C5" },
        { token: "delimiter", foreground: "D4D4D4" },
      ],
      colors: {
        "editor.background": "#1E1E1E",
        "editor.foreground": "#CCCCCC",
        "editorCursor.foreground": "#AEAFAD",
        "editor.lineHighlightBackground": "#2A2A2A",
        "editorLineNumber.foreground": "#858585",
        "editorLineNumber.activeForeground": "#C6C6C6",
        "editor.selectionBackground": "#3A3D41",
        "editor.inactiveSelectionBackground": "#2D2D2D",
        "editorIndentGuide.background": "#333333",
        "editorIndentGuide.activeBackground": "#454545",
        "editorSuggestWidget.background": "#252526",
        "editorSuggestWidget.border": "#454545",
        "editorSuggestWidget.foreground": "#CCCCCC",
        "editorSuggestWidget.selectedBackground": "#37373D",
        "editorSuggestWidget.highlightForeground": "#0078D4",
        "editorSuggestWidget.focusHighlightForeground": "#007ACC",
      },
    },
  },

  "hc-dark": {
    id: "hc-dark",
    name: "High Contrast Dark",
    category: "dark",
    description: "Maximum accessibility dark theme with high contrast borders and vivid highlights.",
    colors: {
      background: "#000000",
      foreground: "#FFFFFF",
      card: "#000000",
      cardForeground: "#FFFFFF",
      popover: "#000000",
      popoverForeground: "#FFFFFF",
      primary: "#1AEBFF",
      primaryForeground: "#000000",
      secondary: "#121212",
      secondaryForeground: "#FFFFFF",
      muted: "#121212",
      mutedForeground: "#CCCCCC",
      accent: "#1AEBFF",
      accentForeground: "#000000",
      border: "#FFFFFF",
      input: "#000000",
      ring: "#1AEBFF",
      success: "#00FF00",
      warning: "#FFFF00",
      destructive: "#FF6B6B",
      info: "#1AEBFF",
      sidebar: "#000000",
      sidebarForeground: "#FFFFFF",
      sidebarPrimary: "#1AEBFF",
      sidebarPrimaryForeground: "#000000",
      sidebarAccent: "#1A1A1A",
      sidebarAccentForeground: "#FFFFFF",
      sidebarBorder: "#FFFFFF",
      sidebarRing: "#1AEBFF",
    },
    monaco: {
      base: "hc-black",
      rules: [
        { token: "comment", foreground: "7CA668", fontStyle: "italic" },
        { token: "keyword", foreground: "569CD6" },
        { token: "string", foreground: "CE9178" },
        { token: "number", foreground: "B5CEA8" },
        { token: "type", foreground: "4EC9B0" },
        { token: "class", foreground: "4EC9B0" },
        { token: "function", foreground: "DCDCAA" },
        { token: "variable", foreground: "9CDCFE" },
        { token: "delimiter", foreground: "FFFFFF" },
      ],
      colors: {
        "editor.background": "#000000",
        "editor.foreground": "#FFFFFF",
        "editorCursor.foreground": "#FFFFFF",
        "editor.lineHighlightBackground": "#1A1A1A",
        "editorLineNumber.foreground": "#FFFFFF",
        "editorLineNumber.activeForeground": "#FFFFFF",
        "editor.selectionBackground": "#264F78",
        "editor.inactiveSelectionBackground": "#1A1A1A",
        "editorIndentGuide.background": "#FFFFFF",
        "editorIndentGuide.activeBackground": "#1AEBFF",
        "editorSuggestWidget.background": "#000000",
        "editorSuggestWidget.border": "#FFFFFF",
        "editorSuggestWidget.foreground": "#FFFFFF",
        "editorSuggestWidget.selectedBackground": "#264F78",
        "editorSuggestWidget.highlightForeground": "#1AEBFF",
        "editorSuggestWidget.focusHighlightForeground": "#1AEBFF",
      },
    },
  },

  "midnight-blue": {
    id: "midnight-blue",
    name: "Midnight Blue",
    category: "dark",
    description: "Deep nocturnal blue palette engineered for soothing night-time development.",
    colors: {
      background: "#0B1120",
      foreground: "#D6E2F0",
      card: "#0F172A",
      cardForeground: "#D6E2F0",
      popover: "#162033",
      popoverForeground: "#F8FAFC",
      primary: "#4FC1FF",
      primaryForeground: "#0B1120",
      secondary: "#1E293B",
      secondaryForeground: "#F8FAFC",
      muted: "#162033",
      mutedForeground: "#94A3B8",
      accent: "#1E293B",
      accentForeground: "#38BDF8",
      border: "#26344A",
      input: "#172033",
      ring: "#4FC1FF",
      success: "#4ADE80",
      warning: "#FBBF24",
      destructive: "#F87171",
      info: "#60A5FA",
      sidebar: "#0B1120",
      sidebarForeground: "#D6E2F0",
      sidebarPrimary: "#4FC1FF",
      sidebarPrimaryForeground: "#0B1120",
      sidebarAccent: "#1E293B",
      sidebarAccentForeground: "#F8FAFC",
      sidebarBorder: "#26344A",
      sidebarRing: "#4FC1FF",
    },
    monaco: {
      base: "vs-dark",
      rules: [
        { token: "comment", foreground: "64748B", fontStyle: "italic" },
        { token: "keyword", foreground: "38BDF8" },
        { token: "string", foreground: "4ADE80" },
        { token: "number", foreground: "FBBF24" },
        { token: "type", foreground: "818CF8" },
        { token: "class", foreground: "818CF8" },
        { token: "function", foreground: "60A5FA" },
        { token: "variable", foreground: "F8FAFC" },
        { token: "delimiter", foreground: "94A3B8" },
      ],
      colors: {
        "editor.background": "#0F172A",
        "editor.foreground": "#D6E2F0",
        "editorCursor.foreground": "#38BDF8",
        "editor.lineHighlightBackground": "#172544",
        "editorLineNumber.foreground": "#475569",
        "editorLineNumber.activeForeground": "#D6E2F0",
        "editor.selectionBackground": "#1E3A5F",
        "editor.inactiveSelectionBackground": "#162033",
        "editorIndentGuide.background": "#1E293B",
        "editorIndentGuide.activeBackground": "#38BDF8",
        "editorSuggestWidget.background": "#162033",
        "editorSuggestWidget.border": "#26344A",
        "editorSuggestWidget.foreground": "#D6E2F0",
        "editorSuggestWidget.selectedBackground": "#1E3A5F",
        "editorSuggestWidget.highlightForeground": "#38BDF8",
        "editorSuggestWidget.focusHighlightForeground": "#60A5FA",
      },
    },
  },

  graphite: {
    id: "graphite",
    name: "Graphite",
    category: "dark",
    description: "Premium neutral monochrome palette with crisp cool accents.",
    colors: {
      background: "#141414",
      foreground: "#D4D4D4",
      card: "#1C1C1C",
      cardForeground: "#D4D4D4",
      popover: "#222222",
      popoverForeground: "#F5F5F5",
      primary: "#8AB4F8",
      primaryForeground: "#141414",
      secondary: "#2A2A2A",
      secondaryForeground: "#F5F5F5",
      muted: "#222222",
      mutedForeground: "#A3A3A3",
      accent: "#2A2A2A",
      accentForeground: "#F5F5F5",
      border: "#303030",
      input: "#242424",
      ring: "#8AB4F8",
      success: "#81C995",
      warning: "#F9C74F",
      destructive: "#F28B82",
      info: "#8AB4F8",
      sidebar: "#151515",
      sidebarForeground: "#D4D4D4",
      sidebarPrimary: "#8AB4F8",
      sidebarPrimaryForeground: "#141414",
      sidebarAccent: "#2A2A2A",
      sidebarAccentForeground: "#F5F5F5",
      sidebarBorder: "#303030",
      sidebarRing: "#8AB4F8",
    },
    monaco: {
      base: "vs-dark",
      rules: [
        { token: "comment", foreground: "737373", fontStyle: "italic" },
        { token: "keyword", foreground: "8AB4F8" },
        { token: "string", foreground: "81C995" },
        { token: "number", foreground: "F9C74F" },
        { token: "type", foreground: "C58AF9" },
        { token: "class", foreground: "C58AF9" },
        { token: "function", foreground: "A8C7FA" },
        { token: "variable", foreground: "F5F5F5" },
        { token: "delimiter", foreground: "A3A3A3" },
      ],
      colors: {
        "editor.background": "#191919",
        "editor.foreground": "#D4D4D4",
        "editorCursor.foreground": "#8AB4F8",
        "editor.lineHighlightBackground": "#242424",
        "editorLineNumber.foreground": "#525252",
        "editorLineNumber.activeForeground": "#D4D4D4",
        "editor.selectionBackground": "#3A3A3A",
        "editor.inactiveSelectionBackground": "#262626",
        "editorIndentGuide.background": "#262626",
        "editorIndentGuide.activeBackground": "#525252",
        "editorSuggestWidget.background": "#222222",
        "editorSuggestWidget.border": "#303030",
        "editorSuggestWidget.foreground": "#D4D4D4",
        "editorSuggestWidget.selectedBackground": "#3A3A3A",
        "editorSuggestWidget.highlightForeground": "#8AB4F8",
        "editorSuggestWidget.focusHighlightForeground": "#A8C7FA",
      },
    },
  },

  "forest-dark": {
    id: "forest-dark",
    name: "Forest Dark",
    category: "dark",
    description: "Natural dark pine and emerald tones for an organic focus environment.",
    colors: {
      background: "#101613",
      foreground: "#D6E4DB",
      card: "#17201B",
      cardForeground: "#D6E4DB",
      popover: "#1D2922",
      popoverForeground: "#F2F8F4",
      primary: "#6CCB8E",
      primaryForeground: "#101613",
      secondary: "#26352C",
      secondaryForeground: "#F2F8F4",
      muted: "#1D2922",
      mutedForeground: "#9CAF9F",
      accent: "#26352C",
      accentForeground: "#86D9A2",
      border: "#304238",
      input: "#202B25",
      ring: "#6CCB8E",
      success: "#6CCB8E",
      warning: "#E5C07B",
      destructive: "#E06C75",
      info: "#6CB6FF",
      sidebar: "#101613",
      sidebarForeground: "#D6E4DB",
      sidebarPrimary: "#6CCB8E",
      sidebarPrimaryForeground: "#101613",
      sidebarAccent: "#26352C",
      sidebarAccentForeground: "#F2F8F4",
      sidebarBorder: "#304238",
      sidebarRing: "#6CCB8E",
    },
    monaco: {
      base: "vs-dark",
      rules: [
        { token: "comment", foreground: "68796E", fontStyle: "italic" },
        { token: "keyword", foreground: "6CCB8E" },
        { token: "string", foreground: "E5C07B" },
        { token: "number", foreground: "E06C75" },
        { token: "type", foreground: "86D9A2" },
        { token: "class", foreground: "86D9A2" },
        { token: "function", foreground: "6CB6FF" },
        { token: "variable", foreground: "F2F8F4" },
        { token: "delimiter", foreground: "9CAF9F" },
      ],
      colors: {
        "editor.background": "#141B17",
        "editor.foreground": "#D6E4DB",
        "editorCursor.foreground": "#6CCB8E",
        "editor.lineHighlightBackground": "#1B2620",
        "editorLineNumber.foreground": "#4A5E52",
        "editorLineNumber.activeForeground": "#D6E4DB",
        "editor.selectionBackground": "#244635",
        "editor.inactiveSelectionBackground": "#1B2620",
        "editorIndentGuide.background": "#202B25",
        "editorIndentGuide.activeBackground": "#4A5E52",
        "editorSuggestWidget.background": "#1D2922",
        "editorSuggestWidget.border": "#304238",
        "editorSuggestWidget.foreground": "#D6E4DB",
        "editorSuggestWidget.selectedBackground": "#26352C",
        "editorSuggestWidget.highlightForeground": "#6CCB8E",
        "editorSuggestWidget.focusHighlightForeground": "#86D9A2",
      },
    },
  },

  // ─── LIGHT THEMES (7) ──────────────────────────────────────────────────────
  "light-modern": {
    id: "light-modern",
    name: "Light Modern",
    category: "light",
    description: "Default modern VS Code light theme with crisp, clean contrast.",
    colors: {
      background: "#F8F8F8",
      foreground: "#3B3B3B",
      card: "#FFFFFF",
      cardForeground: "#3B3B3B",
      popover: "#FFFFFF",
      popoverForeground: "#1F1F1F",
      primary: "#005FB8",
      primaryForeground: "#FFFFFF",
      secondary: "#F2F2F2",
      secondaryForeground: "#1F1F1F",
      muted: "#F2F2F2",
      mutedForeground: "#616161",
      accent: "#F2F2F2",
      accentForeground: "#1F1F1F",
      border: "#E5E5E5",
      input: "#FFFFFF",
      ring: "#005FB8",
      success: "#2EA043",
      warning: "#BB8009",
      destructive: "#F85149",
      info: "#005FB8",
      sidebar: "#F8F8F8",
      sidebarForeground: "#3B3B3B",
      sidebarPrimary: "#005FB8",
      sidebarPrimaryForeground: "#FFFFFF",
      sidebarAccent: "#EAEAEA",
      sidebarAccentForeground: "#1F1F1F",
      sidebarBorder: "#E5E5E5",
      sidebarRing: "#005FB8",
    },
    monaco: {
      base: "vs",
      rules: [
        { token: "comment", foreground: "008000", fontStyle: "italic" },
        { token: "keyword", foreground: "0000FF" },
        { token: "string", foreground: "A31515" },
        { token: "number", foreground: "098658" },
        { token: "type", foreground: "267F99" },
        { token: "class", foreground: "267F99" },
        { token: "function", foreground: "795E26" },
        { token: "variable", foreground: "001080" },
        { token: "delimiter", foreground: "3B3B3B" },
      ],
      colors: {
        "editor.background": "#FFFFFF",
        "editor.foreground": "#3B3B3B",
        "editorCursor.foreground": "#005FB8",
        "editor.lineHighlightBackground": "#F7F7F7",
        "editorLineNumber.foreground": "#616161",
        "editorLineNumber.activeForeground": "#1F1F1F",
        "editor.selectionBackground": "#E5EBF1",
        "editor.inactiveSelectionBackground": "#F0F0F0",
        "editorIndentGuide.background": "#E5E5E5",
        "editorIndentGuide.activeBackground": "#B5B5B5",
        "editorSuggestWidget.background": "#FFFFFF",
        "editorSuggestWidget.border": "#E5E5E5",
        "editorSuggestWidget.foreground": "#3B3B3B",
        "editorSuggestWidget.selectedBackground": "#E5EBF1",
        "editorSuggestWidget.highlightForeground": "#005FB8",
        "editorSuggestWidget.focusHighlightForeground": "#005FB8",
      },
    },
  },

  "light-plus": {
    id: "light-plus",
    name: "Light+",
    category: "light",
    description: "Classic VS Code Light+ theme with familiar editor syntax palette.",
    colors: {
      background: "#FFFFFF",
      foreground: "#000000",
      card: "#FFFFFF",
      cardForeground: "#000000",
      popover: "#FFFFFF",
      popoverForeground: "#000000",
      primary: "#007ACC",
      primaryForeground: "#FFFFFF",
      secondary: "#ECECEC",
      secondaryForeground: "#000000",
      muted: "#F3F3F3",
      mutedForeground: "#717171",
      accent: "#E8E8E8",
      accentForeground: "#000000",
      border: "#E7E7E7",
      input: "#FFFFFF",
      ring: "#007ACC",
      success: "#008000",
      warning: "#A31515",
      destructive: "#CD3131",
      info: "#006AB1",
      sidebar: "#F3F3F3",
      sidebarForeground: "#000000",
      sidebarPrimary: "#007ACC",
      sidebarPrimaryForeground: "#FFFFFF",
      sidebarAccent: "#E5E5E5",
      sidebarAccentForeground: "#000000",
      sidebarBorder: "#E7E7E7",
      sidebarRing: "#007ACC",
    },
    monaco: {
      base: "vs",
      rules: [
        { token: "comment", foreground: "008000", fontStyle: "italic" },
        { token: "keyword", foreground: "AF00DB" },
        { token: "string", foreground: "A31515" },
        { token: "number", foreground: "098658" },
        { token: "type", foreground: "267F99" },
        { token: "class", foreground: "267F99" },
        { token: "function", foreground: "795E26" },
        { token: "variable", foreground: "001080" },
        { token: "delimiter", foreground: "000000" },
      ],
      colors: {
        "editor.background": "#FFFFFF",
        "editor.foreground": "#000000",
        "editorCursor.foreground": "#000000",
        "editor.lineHighlightBackground": "#F5F5F5",
        "editorLineNumber.foreground": "#237893",
        "editorLineNumber.activeForeground": "#0B216F",
        "editor.selectionBackground": "#ADD6FF",
        "editor.inactiveSelectionBackground": "#E5EBF1",
        "editorIndentGuide.background": "#E7E7E7",
        "editorIndentGuide.activeBackground": "#B5B5B5",
        "editorSuggestWidget.background": "#FFFFFF",
        "editorSuggestWidget.border": "#E7E7E7",
        "editorSuggestWidget.foreground": "#000000",
        "editorSuggestWidget.selectedBackground": "#ADD6FF",
        "editorSuggestWidget.highlightForeground": "#007ACC",
        "editorSuggestWidget.focusHighlightForeground": "#006AB1",
      },
    },
  },

  "vs-light": {
    id: "vs-light",
    name: "Visual Studio Light",
    category: "light",
    description: "Classic Visual Studio IDE light workbench.",
    colors: {
      background: "#F8F8F8",
      foreground: "#3B3B3B",
      card: "#F8F8F8",
      cardForeground: "#3B3B3B",
      popover: "#FFFFFF",
      popoverForeground: "#1E1E1E",
      primary: "#005FB8",
      primaryForeground: "#FFFFFF",
      secondary: "#F2F2F2",
      secondaryForeground: "#1F1F1F",
      muted: "#F0F0F0",
      mutedForeground: "#868686",
      accent: "#F2F2F2",
      accentForeground: "#1F1F1F",
      border: "#E5E5E5",
      input: "#FFFFFF",
      ring: "#005FB8",
      success: "#2EA043",
      warning: "#BB8009",
      destructive: "#F85149",
      info: "#0288D1",
      sidebar: "#F3F3F3",
      sidebarForeground: "#3B3B3B",
      sidebarPrimary: "#005FB8",
      sidebarPrimaryForeground: "#FFFFFF",
      sidebarAccent: "#E5E5E5",
      sidebarAccentForeground: "#1E1E1E",
      sidebarBorder: "#E5E5E5",
      sidebarRing: "#005FB8",
    },
    monaco: {
      base: "vs",
      rules: [
        { token: "comment", foreground: "008000", fontStyle: "italic" },
        { token: "keyword", foreground: "0000FF" },
        { token: "string", foreground: "A31515" },
        { token: "number", foreground: "098658" },
        { token: "type", foreground: "267F99" },
        { token: "class", foreground: "267F99" },
        { token: "function", foreground: "795E26" },
        { token: "variable", foreground: "001080" },
        { token: "delimiter", foreground: "3B3B3B" },
      ],
      colors: {
        "editor.background": "#FFFFFF",
        "editor.foreground": "#3B3B3B",
        "editorCursor.foreground": "#005FB8",
        "editor.lineHighlightBackground": "#F7F7F7",
        "editorLineNumber.foreground": "#868686",
        "editorLineNumber.activeForeground": "#1F1F1F",
        "editor.selectionBackground": "#E5EBF1",
        "editor.inactiveSelectionBackground": "#F0F0F0",
        "editorIndentGuide.background": "#E5E5E5",
        "editorIndentGuide.activeBackground": "#B5B5B5",
        "editorSuggestWidget.background": "#FFFFFF",
        "editorSuggestWidget.border": "#E5E5E5",
        "editorSuggestWidget.foreground": "#3B3B3B",
        "editorSuggestWidget.selectedBackground": "#E5EBF1",
        "editorSuggestWidget.highlightForeground": "#005FB8",
        "editorSuggestWidget.focusHighlightForeground": "#005FB8",
      },
    },
  },

  "hc-light": {
    id: "hc-light",
    name: "High Contrast Light",
    category: "light",
    description: "Maximum accessibility light theme with high contrast borders and clean black foregrounds.",
    colors: {
      background: "#FFFFFF",
      foreground: "#000000",
      card: "#FFFFFF",
      cardForeground: "#000000",
      popover: "#FFFFFF",
      popoverForeground: "#000000",
      primary: "#005FB8",
      primaryForeground: "#FFFFFF",
      secondary: "#EEEEEE",
      secondaryForeground: "#000000",
      muted: "#EEEEEE",
      mutedForeground: "#333333",
      accent: "#ADD6FF",
      accentForeground: "#000000",
      border: "#000000",
      input: "#FFFFFF",
      ring: "#005FB8",
      success: "#008000",
      warning: "#795E00",
      destructive: "#CD3131",
      info: "#005FB8",
      sidebar: "#FFFFFF",
      sidebarForeground: "#000000",
      sidebarPrimary: "#005FB8",
      sidebarPrimaryForeground: "#FFFFFF",
      sidebarAccent: "#EEEEEE",
      sidebarAccentForeground: "#000000",
      sidebarBorder: "#000000",
      sidebarRing: "#005FB8",
    },
    monaco: {
      base: "hc-light",
      rules: [
        { token: "comment", foreground: "008000", fontStyle: "italic" },
        { token: "keyword", foreground: "0000FF" },
        { token: "string", foreground: "A31515" },
        { token: "number", foreground: "098658" },
        { token: "type", foreground: "267F99" },
        { token: "class", foreground: "267F99" },
        { token: "function", foreground: "795E26" },
        { token: "variable", foreground: "001080" },
        { token: "delimiter", foreground: "000000" },
      ],
      colors: {
        "editor.background": "#FFFFFF",
        "editor.foreground": "#000000",
        "editorCursor.foreground": "#000000",
        "editor.lineHighlightBackground": "#F0F0F0",
        "editorLineNumber.foreground": "#000000",
        "editorLineNumber.activeForeground": "#000000",
        "editor.selectionBackground": "#ADD6FF",
        "editor.inactiveSelectionBackground": "#EEEEEE",
        "editorIndentGuide.background": "#000000",
        "editorIndentGuide.activeBackground": "#005FB8",
        "editorSuggestWidget.background": "#FFFFFF",
        "editorSuggestWidget.border": "#000000",
        "editorSuggestWidget.foreground": "#000000",
        "editorSuggestWidget.selectedBackground": "#ADD6FF",
        "editorSuggestWidget.highlightForeground": "#005FB8",
        "editorSuggestWidget.focusHighlightForeground": "#005FB8",
      },
    },
  },

  "arctic-blue": {
    id: "arctic-blue",
    name: "Arctic Blue",
    category: "light",
    description: "Cool icy-blue palette providing clean daylight legibility.",
    colors: {
      background: "#F4F7FB",
      foreground: "#243447",
      card: "#FFFFFF",
      cardForeground: "#243447",
      popover: "#F8FAFD",
      popoverForeground: "#152536",
      primary: "#2563EB",
      primaryForeground: "#FFFFFF",
      secondary: "#EAF0F7",
      secondaryForeground: "#152536",
      muted: "#EAF0F7",
      mutedForeground: "#6B7C93",
      accent: "#EAF0F7",
      accentForeground: "#152536",
      border: "#D8E1EC",
      input: "#FFFFFF",
      ring: "#2563EB",
      success: "#15803D",
      warning: "#B45309",
      destructive: "#DC2626",
      info: "#2563EB",
      sidebar: "#F4F7FB",
      sidebarForeground: "#243447",
      sidebarPrimary: "#2563EB",
      sidebarPrimaryForeground: "#FFFFFF",
      sidebarAccent: "#EAF0F7",
      sidebarAccentForeground: "#152536",
      sidebarBorder: "#D8E1EC",
      sidebarRing: "#2563EB",
    },
    monaco: {
      base: "vs",
      rules: [
        { token: "comment", foreground: "6B7C93", fontStyle: "italic" },
        { token: "keyword", foreground: "2563EB" },
        { token: "string", foreground: "15803D" },
        { token: "number", foreground: "B45309" },
        { token: "type", foreground: "0891B2" },
        { token: "class", foreground: "0891B2" },
        { token: "function", foreground: "1D4ED8" },
        { token: "variable", foreground: "152536" },
        { token: "delimiter", foreground: "6B7C93" },
      ],
      colors: {
        "editor.background": "#FFFFFF",
        "editor.foreground": "#243447",
        "editorCursor.foreground": "#2563EB",
        "editor.lineHighlightBackground": "#F4F7FC",
        "editorLineNumber.foreground": "#6B7C93",
        "editorLineNumber.activeForeground": "#152536",
        "editor.selectionBackground": "#DCEBFA",
        "editor.inactiveSelectionBackground": "#EAF0F7",
        "editorIndentGuide.background": "#D8E1EC",
        "editorIndentGuide.activeBackground": "#2563EB",
        "editorSuggestWidget.background": "#F8FAFD",
        "editorSuggestWidget.border": "#D8E1EC",
        "editorSuggestWidget.foreground": "#243447",
        "editorSuggestWidget.selectedBackground": "#DCEBFA",
        "editorSuggestWidget.highlightForeground": "#2563EB",
        "editorSuggestWidget.focusHighlightForeground": "#1D4ED8",
      },
    },
  },

  "warm-sand": {
    id: "warm-sand",
    name: "Warm Sand",
    category: "light",
    description: "Soft earthy parchment aesthetic that reduces eyestrain during prolonged writing.",
    colors: {
      background: "#F7F3EC",
      foreground: "#3F3A34",
      card: "#FFFCF7",
      cardForeground: "#3F3A34",
      popover: "#FFFCF7",
      popoverForeground: "#29251F",
      primary: "#B45309",
      primaryForeground: "#FFFFFF",
      secondary: "#EEE7DA",
      secondaryForeground: "#29251F",
      muted: "#EEE7DA",
      mutedForeground: "#7A7166",
      accent: "#EEE7DA",
      accentForeground: "#29251F",
      border: "#DED4C5",
      input: "#FFFDF9",
      ring: "#B45309",
      success: "#15803D",
      warning: "#B45309",
      destructive: "#DC2626",
      info: "#2563EB",
      sidebar: "#F4EFE6",
      sidebarForeground: "#3F3A34",
      sidebarPrimary: "#B45309",
      sidebarPrimaryForeground: "#FFFFFF",
      sidebarAccent: "#EEE7DA",
      sidebarAccentForeground: "#29251F",
      sidebarBorder: "#DED4C5",
      sidebarRing: "#B45309",
    },
    monaco: {
      base: "vs",
      rules: [
        { token: "comment", foreground: "7A7166", fontStyle: "italic" },
        { token: "keyword", foreground: "B45309" },
        { token: "string", foreground: "15803D" },
        { token: "number", foreground: "DC2626" },
        { token: "type", foreground: "92400E" },
        { token: "class", foreground: "92400E" },
        { token: "function", foreground: "B45309" },
        { token: "variable", foreground: "29251F" },
        { token: "delimiter", foreground: "7A7166" },
      ],
      colors: {
        "editor.background": "#FFFCF7",
        "editor.foreground": "#3F3A34",
        "editorCursor.foreground": "#B45309",
        "editor.lineHighlightBackground": "#F8F3EA",
        "editorLineNumber.foreground": "#7A7166",
        "editorLineNumber.activeForeground": "#29251F",
        "editor.selectionBackground": "#E8DCC8",
        "editor.inactiveSelectionBackground": "#EEE7DA",
        "editorIndentGuide.background": "#DED4C5",
        "editorIndentGuide.activeBackground": "#B45309",
        "editorSuggestWidget.background": "#FFFCF7",
        "editorSuggestWidget.border": "#DED4C5",
        "editorSuggestWidget.foreground": "#3F3A34",
        "editorSuggestWidget.selectedBackground": "#E8DCC8",
        "editorSuggestWidget.highlightForeground": "#B45309",
        "editorSuggestWidget.focusHighlightForeground": "#92400E",
      },
    },
  },

  "mint-light": {
    id: "mint-light",
    name: "Mint Light",
    category: "light",
    description: "Gentle mint-tinted readable palette with refreshing teal and emerald tones.",
    colors: {
      background: "#F2F8F6",
      foreground: "#243832",
      card: "#FFFFFF",
      cardForeground: "#243832",
      popover: "#F7FBFA",
      popoverForeground: "#172A24",
      primary: "#0F766E",
      primaryForeground: "#FFFFFF",
      secondary: "#E5F2EE",
      secondaryForeground: "#172A24",
      muted: "#E5F2EE",
      mutedForeground: "#6B7F77",
      accent: "#E5F2EE",
      accentForeground: "#172A24",
      border: "#D5E4DF",
      input: "#FFFFFF",
      ring: "#0F766E",
      success: "#15803D",
      warning: "#B45309",
      destructive: "#DC2626",
      info: "#2563EB",
      sidebar: "#F2F8F6",
      sidebarForeground: "#243832",
      sidebarPrimary: "#0F766E",
      sidebarPrimaryForeground: "#FFFFFF",
      sidebarAccent: "#E5F2EE",
      sidebarAccentForeground: "#172A24",
      sidebarBorder: "#D5E4DF",
      sidebarRing: "#0F766E",
    },
    monaco: {
      base: "vs",
      rules: [
        { token: "comment", foreground: "6B7F77", fontStyle: "italic" },
        { token: "keyword", foreground: "0F766E" },
        { token: "string", foreground: "15803D" },
        { token: "number", foreground: "B45309" },
        { token: "type", foreground: "115E59" },
        { token: "class", foreground: "115E59" },
        { token: "function", foreground: "0F766E" },
        { token: "variable", foreground: "172A24" },
        { token: "delimiter", foreground: "6B7F77" },
      ],
      colors: {
        "editor.background": "#FFFFFF",
        "editor.foreground": "#243832",
        "editorCursor.foreground": "#0F766E",
        "editor.lineHighlightBackground": "#F3F9F7",
        "editorLineNumber.foreground": "#6B7F77",
        "editorLineNumber.activeForeground": "#172A24",
        "editor.selectionBackground": "#D4EEE5",
        "editor.inactiveSelectionBackground": "#E5F2EE",
        "editorIndentGuide.background": "#D5E4DF",
        "editorIndentGuide.activeBackground": "#0F766E",
        "editorSuggestWidget.background": "#F7FBFA",
        "editorSuggestWidget.border": "#D5E4DF",
        "editorSuggestWidget.foreground": "#243832",
        "editorSuggestWidget.selectedBackground": "#D4EEE5",
        "editorSuggestWidget.highlightForeground": "#0F766E",
        "editorSuggestWidget.focusHighlightForeground": "#115E59",
      },
    },
  },
};

export const THEME_LIST: ThemeDefinition[] = Object.values(THEME_DEFINITIONS);

export const DARK_THEMES: ThemeDefinition[] = THEME_LIST.filter(
  (t) => t.category === "dark"
);

export const LIGHT_THEMES: ThemeDefinition[] = THEME_LIST.filter(
  (t) => t.category === "light"
);

/**
 * Safely maps any legacy or arbitrary stored theme name to a supported ThemeId or "system".
 */
export function migrateLegacyTheme(rawTheme: string | null | undefined): ThemeId | "system" {
  if (!rawTheme) return "dark-modern";
  switch (rawTheme) {
    case "dark":
    case "github-dark":
    case "dark-modern":
      return "dark-modern";
    case "light":
    case "light-modern":
      return "light-modern";
    case "vs-dark":
      return "vs-dark";
    case "vs-light":
      return "vs-light";
    case "hc-dark":
      return "hc-dark";
    case "hc-light":
      return "hc-light";
    case "midnight-blue":
    case "dracula":
    case "tokyo-night":
      return "midnight-blue";
    case "graphite":
    case "one-dark-pro":
      return "graphite";
    case "forest-dark":
    case "monokai":
      return "forest-dark";
    case "dark-plus":
      return "dark-plus";
    case "light-plus":
      return "light-plus";
    case "arctic-blue":
      return "arctic-blue";
    case "warm-sand":
      return "warm-sand";
    case "mint-light":
      return "mint-light";
    case "system":
      return "system";
    default:
      if (rawTheme.toLowerCase().includes("light")) return "light-modern";
      return "dark-modern";
  }
}

/**
 * Checks whether a given theme preference represents a dark appearance.
 */
export function isDarkTheme(theme: string | null | undefined): boolean {
  const resolved = migrateLegacyTheme(theme);
  if (resolved === "system") {
    if (typeof window !== "undefined") {
      return window.matchMedia("(prefers-color-scheme: dark)").matches;
    }
    return true;
  }
  return [
    "dark-modern",
    "dark-plus",
    "vs-dark",
    "hc-dark",
    "midnight-blue",
    "graphite",
    "forest-dark",
  ].includes(resolved);
}

/**
 * Resolves any theme preference (including "system") to an actual concrete ThemeDefinition.
 */
export function resolveTheme(
  preference: ThemePreference | string | null | undefined,
  prefersDark = true
): ThemeDefinition {
  const resolvedId = migrateLegacyTheme(preference);
  if (resolvedId === "system") {
    const concreteId: ThemeId = prefersDark ? "dark-modern" : "light-modern";
    return THEME_DEFINITIONS[concreteId];
  }
  return THEME_DEFINITIONS[resolvedId] || THEME_DEFINITIONS["dark-modern"];
}

