import {
  IDESettings,
  SettingDefinition,
  SettingsCategory,
} from "./types";

export const DEFAULT_SETTINGS: IDESettings = {
  appearance: {
    theme: "dark",
    uiDensity: "normal",
    fontSize: 13,
    sidebarVisible: true,
    sidebarPosition: "left",
    iconTheme: "seti",
  },
  editor: {
    fontSize: 13,
    fontFamily: "var(--font-mono), 'Geist Mono', Consolas, 'Courier New', monospace",
    fontWeight: "normal",
    tabSize: 2,
    insertSpaces: true,
    wordWrap: "on",
    lineNumbers: "on",
    minimap: true,
    cursorStyle: "line",
    cursorBlinking: "smooth",
    renderWhitespace: "selection",
    bracketPairGuides: true,
    stickyScroll: true,
    smoothScrolling: true,
    formatOnSave: false,
    formatOnPaste: false,
    formatOnType: false,
    confirmCloseUnsaved: true,
  },
  files: {
    autoSave: "afterDelay",
    autoSaveDelay: 1000,
    trimTrailingWhitespace: false,
    insertFinalNewline: false,
    confirmDelete: true,
    encoding: "utf-8",
  },
  explorer: {
    showHidden: false,
    sortMode: "name",
    foldersFirst: true,
    compactMode: false,
    confirmDelete: true,
    autoRefresh: true,
    excludePatterns: ["node_modules", ".git", ".next", "target", "dist"],
  },
  search: {
    isCaseSensitive: false,
    isWholeWord: false,
    isRegex: false,
    includePattern: "",
    excludePattern: "**/node_modules, **/.git, **/.next",
  },
  keyboard: {
    dispatchMode: "global",
  },
};

// eslint-disable-next-line @typescript-eslint/no-explicit-any
export const SETTINGS_REGISTRY: SettingDefinition<any>[] = [
  // ─── APPEARANCE ────────────────────────────────────────────────────────
  {
    key: "appearance.theme",
    category: "appearance",
    label: "Color Theme",
    description: "Specifies the color theme used in the workbench and editor.",
    type: "select",
    defaultValue: "dark",
    scope: "user",
    options: [
      { label: "Kairo Dark", value: "dark" },
      { label: "Kairo Light", value: "light" },
      { label: "System Default", value: "system" },
      { label: "VS Code Dark+", value: "vs-dark" },
      { label: "VS Code Light+", value: "vs-light" },
      { label: "One Dark Pro", value: "one-dark-pro" },
      { label: "Dracula", value: "dracula" },
      { label: "Tokyo Night", value: "tokyo-night" },
      { label: "GitHub Dark", value: "github-dark" },
      { label: "Monokai Pro", value: "monokai" },
    ],
    validate: (val) =>
      [
        "dark",
        "light",
        "system",
        "vs-dark",
        "vs-light",
        "one-dark-pro",
        "dracula",
        "tokyo-night",
        "github-dark",
        "monokai",
      ].includes(val as string),
  },
  {
    key: "appearance.uiDensity",
    category: "appearance",
    label: "UI Density",
    description: "Controls the spacing and sizing of UI elements across panels.",
    type: "select",
    defaultValue: "normal",
    scope: "user",
    options: [
      { label: "Normal", value: "normal" },
      { label: "Compact", value: "compact" },
    ],
    validate: (val) => ["normal", "compact"].includes(val as string),
  },
  {
    key: "appearance.fontSize",
    category: "appearance",
    label: "UI Font Size",
    description: "Controls the base font size for workbench labels and panels in pixels.",
    type: "number",
    defaultValue: 13,
    scope: "user",
    min: 10,
    max: 20,
    step: 1,
    validate: (val) => typeof val === "number" && val >= 10 && val <= 20,
  },
  {
    key: "appearance.iconTheme",
    category: "appearance",
    label: "File Icon Theme",
    description: "Specifies the file icon set used in the explorer and editor tabs.",
    type: "select",
    defaultValue: "seti",
    scope: "user",
    options: [
      { label: "Seti (Custom)", value: "seti" },
    ],
    validate: (val) => typeof val === "string" && val.length > 0,
  },
  {
    key: "appearance.sidebarVisible",
    category: "appearance",
    label: "Sidebar Visible",
    description: "Controls whether the primary sidebar is visible.",
    type: "boolean",
    defaultValue: true,
    scope: "user",
    validate: (val) => typeof val === "boolean",
  },
  {
    key: "appearance.sidebarPosition",
    category: "appearance",
    label: "Sidebar Position",
    description: "Controls the dock position of the primary sidebar.",
    type: "select",
    defaultValue: "left",
    scope: "user",
    options: [
      { label: "Left", value: "left" },
      { label: "Right", value: "right" },
    ],
    validate: (val) => ["left", "right"].includes(val as string),
  },

  // ─── EDITOR ───────────────────────────────────────────────────────────
  {
    key: "editor.fontSize",
    category: "editor",
    label: "Font Size",
    description: "Controls the font size in pixels for the Monaco editor.",
    type: "number",
    defaultValue: 13,
    scope: "both",
    min: 8,
    max: 72,
    step: 1,
    validate: (val) => typeof val === "number" && val >= 8 && val <= 72,
  },
  {
    key: "editor.fontFamily",
    category: "editor",
    label: "Font Family",
    description: "Controls the font family used in the editor.",
    type: "string",
    defaultValue: "var(--font-mono), 'Geist Mono', Consolas, 'Courier New', monospace",
    scope: "both",
    validate: (val) => typeof val === "string" && val.trim().length > 0,
  },
  {
    key: "editor.fontWeight",
    category: "editor",
    label: "Font Weight",
    description: "Controls the font weight in the editor.",
    type: "select",
    defaultValue: "normal",
    scope: "both",
    options: [
      { label: "Normal (400)", value: "normal" },
      { label: "Medium (500)", value: "500" },
      { label: "Semi Bold (600)", value: "600" },
      { label: "Bold (700)", value: "bold" },
    ],
    validate: (val) => typeof val === "string",
  },
  {
    key: "editor.tabSize",
    category: "editor",
    label: "Tab Size",
    description: "The number of spaces a tab is equal to in the editor.",
    type: "number",
    defaultValue: 2,
    scope: "both",
    min: 1,
    max: 16,
    step: 1,
    validate: (val) => typeof val === "number" && val >= 1 && val <= 16,
  },
  {
    key: "editor.insertSpaces",
    category: "editor",
    label: "Insert Spaces",
    description: "Insert spaces when pressing Tab instead of tab characters.",
    type: "boolean",
    defaultValue: true,
    scope: "both",
    validate: (val) => typeof val === "boolean",
  },
  {
    key: "editor.wordWrap",
    category: "editor",
    label: "Word Wrap",
    description: "Controls how lines wrap in the editor.",
    type: "select",
    defaultValue: "on",
    scope: "both",
    options: [
      { label: "On", value: "on" },
      { label: "Off", value: "off" },
      { label: "Word Wrap Column", value: "wordWrapColumn" },
      { label: "Bounded", value: "bounded" },
    ],
    validate: (val) => ["on", "off", "wordWrapColumn", "bounded"].includes(val as string),
  },
  {
    key: "editor.lineNumbers",
    category: "editor",
    label: "Line Numbers",
    description: "Controls the display of line numbers in the editor margin.",
    type: "select",
    defaultValue: "on",
    scope: "both",
    options: [
      { label: "On", value: "on" },
      { label: "Off", value: "off" },
      { label: "Relative", value: "relative" },
    ],
    validate: (val) => ["on", "off", "relative"].includes(val as string),
  },
  {
    key: "editor.minimap",
    category: "editor",
    label: "Minimap",
    description: "Controls whether the code overview minimap is shown on the right side.",
    type: "boolean",
    defaultValue: true,
    scope: "both",
    validate: (val) => typeof val === "boolean",
  },
  {
    key: "editor.cursorStyle",
    category: "editor",
    label: "Cursor Style",
    description: "Controls the style of the text insertion cursor.",
    type: "select",
    defaultValue: "line",
    scope: "both",
    options: [
      { label: "Line", value: "line" },
      { label: "Block", value: "block" },
      { label: "Underline", value: "underline" },
      { label: "Line Thin", value: "line-thin" },
      { label: "Block Outline", value: "block-outline" },
      { label: "Underline Thin", value: "underline-thin" },
    ],
    validate: (val) =>
      ["line", "block", "underline", "line-thin", "block-outline", "underline-thin"].includes(val as string),
  },
  {
    key: "editor.cursorBlinking",
    category: "editor",
    label: "Cursor Blinking",
    description: "Controls the animation style of the editor cursor blinking.",
    type: "select",
    defaultValue: "smooth",
    scope: "both",
    options: [
      { label: "Smooth", value: "smooth" },
      { label: "Blink", value: "blink" },
      { label: "Phase", value: "phase" },
      { label: "Expand", value: "expand" },
      { label: "Solid", value: "solid" },
    ],
    validate: (val) => ["smooth", "blink", "phase", "expand", "solid"].includes(val as string),
  },
  {
    key: "editor.renderWhitespace",
    category: "editor",
    label: "Render Whitespace",
    description: "Controls how whitespace characters are rendered in the editor.",
    type: "select",
    defaultValue: "selection",
    scope: "both",
    options: [
      { label: "None", value: "none" },
      { label: "Boundary", value: "boundary" },
      { label: "Selection", value: "selection" },
      { label: "Trailing", value: "trailing" },
      { label: "All", value: "all" },
    ],
    validate: (val) => ["none", "boundary", "selection", "trailing", "all"].includes(val as string),
  },
  {
    key: "editor.bracketPairGuides",
    category: "editor",
    label: "Bracket Pair Guides",
    description: "Controls whether bracket pair guide lines and colorization are enabled.",
    type: "boolean",
    defaultValue: true,
    scope: "both",
    validate: (val) => typeof val === "boolean",
  },
  {
    key: "editor.stickyScroll",
    category: "editor",
    label: "Sticky Scroll",
    description: "Shows nested current scopes at the top of the editor during scroll.",
    type: "boolean",
    defaultValue: true,
    scope: "both",
    validate: (val) => typeof val === "boolean",
  },
  {
    key: "editor.smoothScrolling",
    category: "editor",
    label: "Smooth Scrolling",
    description: "Controls whether the editor scrolls using smooth animations.",
    type: "boolean",
    defaultValue: true,
    scope: "both",
    validate: (val) => typeof val === "boolean",
  },
  {
    key: "editor.formatOnSave",
    category: "editor",
    label: "Format On Save",
    description: "Automatically formats the active document when saving.",
    type: "boolean",
    defaultValue: false,
    scope: "both",
    validate: (val) => typeof val === "boolean",
  },
  {
    key: "editor.formatOnPaste",
    category: "editor",
    label: "Format On Paste",
    description: "Controls whether the editor automatically formats pasted content.",
    type: "boolean",
    defaultValue: false,
    scope: "both",
    validate: (val) => typeof val === "boolean",
  },
  {
    key: "editor.formatOnType",
    category: "editor",
    label: "Format On Type",
    description: "Controls whether the editor formats lines automatically after typing trigger characters.",
    type: "boolean",
    defaultValue: false,
    scope: "both",
    validate: (val) => typeof val === "boolean",
  },
  {
    key: "editor.confirmCloseUnsaved",
    category: "editor",
    label: "Confirm Close Unsaved Files",
    description: "Prompts confirmation before closing any file tab with unsaved modifications.",
    type: "boolean",
    defaultValue: true,
    scope: "both",
    validate: (val) => typeof val === "boolean",
  },

  // ─── FILES ────────────────────────────────────────────────────────────
  {
    key: "files.autoSave",
    category: "files",
    label: "Auto Save Mode",
    description: "Controls automatic saving of dirty files.",
    type: "select",
    defaultValue: "afterDelay",
    scope: "both",
    options: [
      { label: "Off", value: "off" },
      { label: "After Delay", value: "afterDelay" },
      { label: "On Focus Change", value: "onFocusChange" },
      { label: "On Window Change", value: "onWindowChange" },
    ],
    validate: (val) => ["off", "afterDelay", "onFocusChange", "onWindowChange"].includes(val as string),
  },
  {
    key: "files.autoSaveDelay",
    category: "files",
    label: "Auto Save Delay (ms)",
    description: "Controls the delay in milliseconds before automatically saving an edited file.",
    type: "number",
    defaultValue: 1000,
    scope: "both",
    min: 500,
    max: 10000,
    step: 250,
    validate: (val) => typeof val === "number" && val >= 500 && val <= 10000,
  },
  {
    key: "files.trimTrailingWhitespace",
    category: "files",
    label: "Trim Trailing Whitespace",
    description: "When enabled, trims trailing whitespace when saving a file.",
    type: "boolean",
    defaultValue: false,
    scope: "both",
    validate: (val) => typeof val === "boolean",
  },
  {
    key: "files.insertFinalNewline",
    category: "files",
    label: "Insert Final Newline",
    description: "When enabled, ensures a final newline at end-of-file on save.",
    type: "boolean",
    defaultValue: false,
    scope: "both",
    validate: (val) => typeof val === "boolean",
  },
  {
    key: "files.confirmDelete",
    category: "files",
    label: "Confirm Delete",
    description: "Controls whether confirmation is requested when deleting files through the explorer.",
    type: "boolean",
    defaultValue: true,
    scope: "both",
    validate: (val) => typeof val === "boolean",
  },
  {
    key: "files.encoding",
    category: "files",
    label: "Default File Encoding",
    description: "Default character encoding used to read and write text documents.",
    type: "select",
    defaultValue: "utf-8",
    scope: "both",
    options: [
      { label: "UTF-8", value: "utf-8" },
      { label: "ASCII", value: "ascii" },
    ],
    validate: (val) => typeof val === "string",
  },

  // ─── EXPLORER ─────────────────────────────────────────────────────────
  {
    key: "explorer.showHidden",
    category: "explorer",
    label: "Show Hidden Files",
    description: "Controls whether hidden files (names beginning with a dot) are displayed in the tree.",
    type: "boolean",
    defaultValue: false,
    scope: "both",
    validate: (val) => typeof val === "boolean",
  },
  {
    key: "explorer.sortMode",
    category: "explorer",
    label: "Sort Mode",
    description: "Controls the primary sort ordering of files and folders in the explorer.",
    type: "select",
    defaultValue: "name",
    scope: "both",
    options: [
      { label: "Name (Alphabetical)", value: "name" },
      { label: "File Type / Extension", value: "type" },
      { label: "Last Modified Date", value: "modified" },
      { label: "File Size", value: "size" },
    ],
    validate: (val) => ["name", "type", "modified", "size"].includes(val as string),
  },
  {
    key: "explorer.foldersFirst",
    category: "explorer",
    label: "Folders First",
    description: "Controls whether folders are grouped above files in the tree view.",
    type: "boolean",
    defaultValue: true,
    scope: "both",
    validate: (val) => typeof val === "boolean",
  },
  {
    key: "explorer.compactMode",
    category: "explorer",
    label: "Compact Mode",
    description: "Renders single child folder chains compactly.",
    type: "boolean",
    defaultValue: false,
    scope: "both",
    validate: (val) => typeof val === "boolean",
  },
  {
    key: "explorer.confirmDelete",
    category: "explorer",
    label: "Confirm Explorer Deletions",
    description: "Asks for confirmation when permanently deleting items from the explorer.",
    type: "boolean",
    defaultValue: true,
    scope: "both",
    validate: (val) => typeof val === "boolean",
  },
  {
    key: "explorer.autoRefresh",
    category: "explorer",
    label: "Auto Refresh",
    description: "Automatically refreshes file tree when filesystem changes occur.",
    type: "boolean",
    defaultValue: true,
    scope: "both",
    validate: (val) => typeof val === "boolean",
  },

  // ─── SEARCH ───────────────────────────────────────────────────────────
  {
    key: "search.isCaseSensitive",
    category: "search",
    label: "Match Case by Default",
    description: "Controls whether workspace search defaults to case-sensitive matching.",
    type: "boolean",
    defaultValue: false,
    scope: "both",
    validate: (val) => typeof val === "boolean",
  },
  {
    key: "search.isWholeWord",
    category: "search",
    label: "Match Whole Word by Default",
    description: "Controls whether workspace search defaults to whole-word matching.",
    type: "boolean",
    defaultValue: false,
    scope: "both",
    validate: (val) => typeof val === "boolean",
  },
  {
    key: "search.isRegex",
    category: "search",
    label: "Use Regular Expressions by Default",
    description: "Controls whether workspace search defaults to interpreting queries as regular expressions.",
    type: "boolean",
    defaultValue: false,
    scope: "both",
    validate: (val) => typeof val === "boolean",
  },
  {
    key: "search.excludePattern",
    category: "search",
    label: "Search Exclude Patterns",
    description: "Default glob patterns to exclude from workspace searches (comma separated).",
    type: "string",
    defaultValue: "**/node_modules, **/.git, **/.next",
    scope: "both",
    validate: (val) => typeof val === "string",
  },
];

export function getSettingDefinition(key: string): SettingDefinition | undefined {
  return SETTINGS_REGISTRY.find((s) => s.key === key);
}

export function getCategoryDefinitions(category: SettingsCategory): SettingDefinition[] {
  return SETTINGS_REGISTRY.filter((s) => s.category === category);
}

export function searchDefinitions(query: string): SettingDefinition[] {
  const clean = query.trim().toLowerCase();
  if (!clean) return SETTINGS_REGISTRY;

  return SETTINGS_REGISTRY.filter((s) => {
    return (
      s.key.toLowerCase().includes(clean) ||
      s.label.toLowerCase().includes(clean) ||
      s.description.toLowerCase().includes(clean) ||
      s.category.toLowerCase().includes(clean)
    );
  });
}

