import { IconTheme, IconDefinition } from "../types";
import {
  SetiTypeScriptIcon,
  SetiReactTsIcon,
  SetiJavaScriptIcon,
  SetiReactJsIcon,
  SetiPythonIcon,
  SetiRustIcon,
  SetiGoIcon,
  SetiJavaIcon,
  SetiCppIcon,
  SetiCIcon,
  SetiCSharpIcon,
  SetiPhpIcon,
  SetiRubyIcon,
  SetiSwiftIcon,
  SetiKotlinIcon,
  SetiDartIcon,
  SetiHtmlIcon,
  SetiCssIcon,
  SetiSassIcon,
  SetiJsonIcon,
  SetiYamlIcon,
  SetiMarkdownIcon,
  SetiShellIcon,
  SetiSqlIcon,
  SetiGitIcon,
  SetiDockerIcon,
  SetiNpmIcon,
  SetiYarnIcon,
  SetiPnpmIcon,
  SetiViteIcon,
  SetiNextJsIcon,
  SetiTailwindIcon,
  SetiEslintIcon,
  SetiEnvIcon,
  SetiSettingsIcon,
  SetiLicenseIcon,
  SetiImageIcon,
  SetiVideoIcon,
  SetiAudioIcon,
  SetiArchiveIcon,
  SetiDefaultFileIcon,
  SetiFolderClosedIcon,
  SetiFolderOpenIcon,
  SetiSrcFolderClosed,
  SetiSrcFolderOpen,
  SetiComponentsFolderClosed,
  SetiComponentsFolderOpen,
  SetiAppFolderClosed,
  SetiAppFolderOpen,
  SetiPublicFolderClosed,
  SetiPublicFolderOpen,
  SetiAssetsFolderClosed,
  SetiAssetsFolderOpen,
  SetiTestFolderClosed,
  SetiTestFolderOpen,
  SetiNodeModulesFolderClosed,
  SetiNodeModulesFolderOpen,
  SetiGitFolderClosed,
  SetiGitFolderOpen,
  SetiVscodeFolderClosed,
  SetiVscodeFolderOpen,
} from "../components/seti-svgs";

export const setiDefinitions: Record<string, IconDefinition> = {
  // Languages
  typescript: { id: "seti-typescript", name: "TypeScript", render: SetiTypeScriptIcon, color: "#3178C6" },
  reactTs: { id: "seti-react-ts", name: "React TypeScript", render: SetiReactTsIcon, color: "#00D8FF" },
  javascript: { id: "seti-javascript", name: "JavaScript", render: SetiJavaScriptIcon, color: "#F7DF1E" },
  reactJs: { id: "seti-react-js", name: "React JavaScript", render: SetiReactJsIcon, color: "#00D8FF" },
  python: { id: "seti-python", name: "Python", render: SetiPythonIcon, color: "#3572A5" },
  rust: { id: "seti-rust", name: "Rust", render: SetiRustIcon, color: "#CE412B" },
  go: { id: "seti-go", name: "Go", render: SetiGoIcon, color: "#00ADD8" },
  java: { id: "seti-java", name: "Java", render: SetiJavaIcon, color: "#E76F00" },
  cpp: { id: "seti-cpp", name: "C++", render: SetiCppIcon, color: "#00599C" },
  c: { id: "seti-c", name: "C", render: SetiCIcon, color: "#555555" },
  csharp: { id: "seti-csharp", name: "C#", render: SetiCSharpIcon, color: "#68217A" },
  php: { id: "seti-php", name: "PHP", render: SetiPhpIcon, color: "#777BB4" },
  ruby: { id: "seti-ruby", name: "Ruby", render: SetiRubyIcon, color: "#CC342D" },
  swift: { id: "seti-swift", name: "Swift", render: SetiSwiftIcon, color: "#F05138" },
  kotlin: { id: "seti-kotlin", name: "Kotlin", render: SetiKotlinIcon, color: "#7F52FF" },
  dart: { id: "seti-dart", name: "Dart", render: SetiDartIcon, color: "#00B4AB" },
  html: { id: "seti-html", name: "HTML", render: SetiHtmlIcon, color: "#E34F26" },
  css: { id: "seti-css", name: "CSS", render: SetiCssIcon, color: "#1572B6" },
  sass: { id: "seti-sass", name: "Sass", render: SetiSassIcon, color: "#CC6699" },
  json: { id: "seti-json", name: "JSON", render: SetiJsonIcon, color: "#CBCB41" },
  yaml: { id: "seti-yaml", name: "YAML", render: SetiYamlIcon, color: "#CB171E" },
  markdown: { id: "seti-markdown", name: "Markdown", render: SetiMarkdownIcon, color: "#519ABA" },
  shell: { id: "seti-shell", name: "Shell", render: SetiShellIcon, color: "#A3BE8C" },
  sql: { id: "seti-sql", name: "SQL", render: SetiSqlIcon, color: "#E38C00" },

  // Tools & Configs
  git: { id: "seti-git", name: "Git", render: SetiGitIcon, color: "#F14E32" },
  docker: { id: "seti-docker", name: "Docker", render: SetiDockerIcon, color: "#0DB7ED" },
  npm: { id: "seti-npm", name: "NPM", render: SetiNpmIcon, color: "#CB3837" },
  yarn: { id: "seti-yarn", name: "Yarn", render: SetiYarnIcon, color: "#2C8EBB" },
  pnpm: { id: "seti-pnpm", name: "PNPM", render: SetiPnpmIcon, color: "#F9AD00" },
  vite: { id: "seti-vite", name: "Vite", render: SetiViteIcon, color: "#646CFF" },
  nextjs: { id: "seti-nextjs", name: "Next.js", render: SetiNextJsIcon, color: "#000000" },
  tailwind: { id: "seti-tailwind", name: "Tailwind CSS", render: SetiTailwindIcon, color: "#38BDF8" },
  eslint: { id: "seti-eslint", name: "ESLint", render: SetiEslintIcon, color: "#4B32C3" },
  env: { id: "seti-env", name: "Environment", render: SetiEnvIcon, color: "#ECD53F" },
  settings: { id: "seti-settings", name: "Settings", render: SetiSettingsIcon, color: "#8C8C8C" },
  license: { id: "seti-license", name: "License", render: SetiLicenseIcon, color: "#E38C00" },

  // Media
  image: { id: "seti-image", name: "Image", render: SetiImageIcon, color: "#A074C4" },
  video: { id: "seti-video", name: "Video", render: SetiVideoIcon, color: "#8A63D2" },
  audio: { id: "seti-audio", name: "Audio", render: SetiAudioIcon, color: "#E06C75" },
  archive: { id: "seti-archive", name: "Archive", render: SetiArchiveIcon, color: "#CCA152" },

  // Fallbacks & Defaults
  defaultFile: { id: "seti-default-file", name: "File", render: SetiDefaultFileIcon, color: "#8A8A8A" },
  defaultFolder: { id: "seti-default-folder", name: "Folder", render: SetiFolderClosedIcon, color: "#DCB67A" },
  defaultFolderExpanded: { id: "seti-default-folder-expanded", name: "Folder (Open)", render: SetiFolderOpenIcon, color: "#DCB67A" },

  // Specialized Folders
  srcFolder: { id: "seti-folder-src", name: "Source Folder", render: SetiSrcFolderClosed, color: "#DCB67A" },
  srcFolderOpen: { id: "seti-folder-src-open", name: "Source Folder (Open)", render: SetiSrcFolderOpen, color: "#DCB67A" },
  componentsFolder: { id: "seti-folder-components", name: "Components Folder", render: SetiComponentsFolderClosed, color: "#DCB67A" },
  componentsFolderOpen: { id: "seti-folder-components-open", name: "Components Folder (Open)", render: SetiComponentsFolderOpen, color: "#DCB67A" },
  appFolder: { id: "seti-folder-app", name: "App Folder", render: SetiAppFolderClosed, color: "#DCB67A" },
  appFolderOpen: { id: "seti-folder-app-open", name: "App Folder (Open)", render: SetiAppFolderOpen, color: "#DCB67A" },
  publicFolder: { id: "seti-folder-public", name: "Public Folder", render: SetiPublicFolderClosed, color: "#DCB67A" },
  publicFolderOpen: { id: "seti-folder-public-open", name: "Public Folder (Open)", render: SetiPublicFolderOpen, color: "#DCB67A" },
  assetsFolder: { id: "seti-folder-assets", name: "Assets Folder", render: SetiAssetsFolderClosed, color: "#DCB67A" },
  assetsFolderOpen: { id: "seti-folder-assets-open", name: "Assets Folder (Open)", render: SetiAssetsFolderOpen, color: "#DCB67A" },
  testFolder: { id: "seti-folder-test", name: "Test Folder", render: SetiTestFolderClosed, color: "#DCB67A" },
  testFolderOpen: { id: "seti-folder-test-open", name: "Test Folder (Open)", render: SetiTestFolderOpen, color: "#DCB67A" },
  nodeModulesFolder: { id: "seti-folder-node-modules", name: "Node Modules Folder", render: SetiNodeModulesFolderClosed, color: "#DCB67A" },
  nodeModulesFolderOpen: { id: "seti-folder-node-modules-open", name: "Node Modules Folder (Open)", render: SetiNodeModulesFolderOpen, color: "#DCB67A" },
  gitFolder: { id: "seti-folder-git", name: "Git Folder", render: SetiGitFolderClosed, color: "#DCB67A" },
  gitFolderOpen: { id: "seti-folder-git-open", name: "Git Folder (Open)", render: SetiGitFolderOpen, color: "#DCB67A" },
  vscodeFolder: { id: "seti-folder-vscode", name: "VS Code Folder", render: SetiVscodeFolderClosed, color: "#DCB67A" },
  vscodeFolderOpen: { id: "seti-folder-vscode-open", name: "VS Code Folder (Open)", render: SetiVscodeFolderOpen, color: "#DCB67A" },
};

export const setiTheme: IconTheme = {
  id: "seti",
  name: "Seti (Visual Studio Code)",
  defaultFile: setiDefinitions.defaultFile,
  defaultFolder: setiDefinitions.defaultFolder,
  defaultFolderExpanded: setiDefinitions.defaultFolderExpanded,

  exactFiles: {
    // Node / Package managers
    "package.json": setiDefinitions.npm,
    "package-lock.json": setiDefinitions.npm,
    "yarn.lock": setiDefinitions.yarn,
    ".yarnrc": setiDefinitions.yarn,
    ".yarnrc.yml": setiDefinitions.yarn,
    "pnpm-lock.yaml": setiDefinitions.pnpm,
    "pnpm-workspace.yaml": setiDefinitions.pnpm,

    // TypeScript / JavaScript config
    "tsconfig.json": setiDefinitions.typescript,
    "tsconfig.app.json": setiDefinitions.typescript,
    "tsconfig.node.json": setiDefinitions.typescript,
    "jsconfig.json": setiDefinitions.javascript,

    // Bundlers / Frameworks
    "vite.config.ts": setiDefinitions.vite,
    "vite.config.js": setiDefinitions.vite,
    "vite.config.mjs": setiDefinitions.vite,
    "next.config.js": setiDefinitions.nextjs,
    "next.config.mjs": setiDefinitions.nextjs,
    "next.config.ts": setiDefinitions.nextjs,
    "tailwind.config.js": setiDefinitions.tailwind,
    "tailwind.config.ts": setiDefinitions.tailwind,
    "tailwind.config.cjs": setiDefinitions.tailwind,
    "tailwind.config.mjs": setiDefinitions.tailwind,
    "postcss.config.js": setiDefinitions.css,
    "postcss.config.mjs": setiDefinitions.css,

    // Linters & Formatters
    "eslint.config.js": setiDefinitions.eslint,
    "eslint.config.mjs": setiDefinitions.eslint,
    "eslint.config.cjs": setiDefinitions.eslint,
    ".eslintrc": setiDefinitions.eslint,
    ".eslintrc.json": setiDefinitions.eslint,
    ".eslintrc.js": setiDefinitions.eslint,
    ".eslintrc.cjs": setiDefinitions.eslint,
    ".eslintignore": setiDefinitions.eslint,
    ".prettierrc": setiDefinitions.settings,
    ".prettierrc.json": setiDefinitions.settings,
    ".prettierrc.js": setiDefinitions.settings,
    ".prettierignore": setiDefinitions.settings,

    // Git
    ".gitignore": setiDefinitions.git,
    ".gitattributes": setiDefinitions.git,
    ".gitmodules": setiDefinitions.git,

    // Environment
    ".env": setiDefinitions.env,
    ".env.local": setiDefinitions.env,
    ".env.development": setiDefinitions.env,
    ".env.production": setiDefinitions.env,
    ".env.test": setiDefinitions.env,
    ".env.example": setiDefinitions.env,

    // Containers & Deployments
    dockerfile: setiDefinitions.docker,
    "dockerfile.dev": setiDefinitions.docker,
    "dockerfile.prod": setiDefinitions.docker,
    "docker-compose.yml": setiDefinitions.docker,
    "docker-compose.yaml": setiDefinitions.docker,
    ".dockerignore": setiDefinitions.docker,

    // Documentation & Legal
    "readme.md": setiDefinitions.markdown,
    readme: setiDefinitions.markdown,
    license: setiDefinitions.license,
    "license.md": setiDefinitions.license,
    "license.txt": setiDefinitions.license,

    // Rust & Tauri
    "cargo.toml": setiDefinitions.rust,
    "cargo.lock": setiDefinitions.rust,
    "tauri.conf.json": setiDefinitions.settings,

    // Editor settings
    "settings.json": setiDefinitions.settings,
  },

  filePatterns: [
    { id: "env-pattern", pattern: /^\.env(\..+)?$/i, icon: setiDefinitions.env },
    { id: "docker-pattern", pattern: /^dockerfile(\..+)?$/i, icon: setiDefinitions.docker },
    { id: "docker-compose-pattern", pattern: /^docker-compose(\..+)?\.ya?ml$/i, icon: setiDefinitions.docker },
    { id: "license-pattern", pattern: /^licen[sc]e(\..+)?$/i, icon: setiDefinitions.license },
    { id: "readme-pattern", pattern: /^readme(\..+)?$/i, icon: setiDefinitions.markdown },
  ],

  fileExtensions: {
    // TypeScript & React
    ts: setiDefinitions.typescript,
    cts: setiDefinitions.typescript,
    mts: setiDefinitions.typescript,
    tsx: setiDefinitions.reactTs,

    // JavaScript & React
    js: setiDefinitions.javascript,
    cjs: setiDefinitions.javascript,
    mjs: setiDefinitions.javascript,
    jsx: setiDefinitions.reactJs,

    // Programming Languages
    py: setiDefinitions.python,
    pyw: setiDefinitions.python,
    pyx: setiDefinitions.python,
    rs: setiDefinitions.rust,
    go: setiDefinitions.go,
    java: setiDefinitions.java,
    c: setiDefinitions.c,
    h: setiDefinitions.c,
    cpp: setiDefinitions.cpp,
    cc: setiDefinitions.cpp,
    cxx: setiDefinitions.cpp,
    hpp: setiDefinitions.cpp,
    hxx: setiDefinitions.cpp,
    hh: setiDefinitions.cpp,
    cs: setiDefinitions.csharp,
    php: setiDefinitions.php,
    phtml: setiDefinitions.php,
    rb: setiDefinitions.ruby,
    erb: setiDefinitions.ruby,
    swift: setiDefinitions.swift,
    kt: setiDefinitions.kotlin,
    kts: setiDefinitions.kotlin,
    dart: setiDefinitions.dart,

    // Web & Styles
    html: setiDefinitions.html,
    htm: setiDefinitions.html,
    xhtml: setiDefinitions.html,
    css: setiDefinitions.css,
    scss: setiDefinitions.sass,
    sass: setiDefinitions.sass,
    less: setiDefinitions.sass,

    // Data & Config formats
    json: setiDefinitions.json,
    json5: setiDefinitions.json,
    jsonc: setiDefinitions.json,
    yaml: setiDefinitions.yaml,
    yml: setiDefinitions.yaml,
    toml: setiDefinitions.settings,
    ini: setiDefinitions.settings,
    conf: setiDefinitions.settings,
    config: setiDefinitions.settings,

    // Documentation
    md: setiDefinitions.markdown,
    markdown: setiDefinitions.markdown,
    mdown: setiDefinitions.markdown,
    mkd: setiDefinitions.markdown,

    // Shell scripts & Database
    sh: setiDefinitions.shell,
    bash: setiDefinitions.shell,
    zsh: setiDefinitions.shell,
    fish: setiDefinitions.shell,
    ps1: setiDefinitions.shell,
    bat: setiDefinitions.shell,
    cmd: setiDefinitions.shell,
    sql: setiDefinitions.sql,

    // Media
    svg: setiDefinitions.image,
    png: setiDefinitions.image,
    jpg: setiDefinitions.image,
    jpeg: setiDefinitions.image,
    gif: setiDefinitions.image,
    webp: setiDefinitions.image,
    ico: setiDefinitions.image,
    bmp: setiDefinitions.image,
    tiff: setiDefinitions.image,
    mp4: setiDefinitions.video,
    webm: setiDefinitions.video,
    mov: setiDefinitions.video,
    mkv: setiDefinitions.video,
    avi: setiDefinitions.video,
    mp3: setiDefinitions.audio,
    wav: setiDefinitions.audio,
    ogg: setiDefinitions.audio,
    flac: setiDefinitions.audio,
    aac: setiDefinitions.audio,

    // Archives
    zip: setiDefinitions.archive,
    tar: setiDefinitions.archive,
    gz: setiDefinitions.archive,
    "7z": setiDefinitions.archive,
    rar: setiDefinitions.archive,
    bz2: setiDefinitions.archive,
  },

  folderNames: {
    src: setiDefinitions.srcFolder,
    app: setiDefinitions.appFolder,
    components: setiDefinitions.componentsFolder,
    pages: setiDefinitions.componentsFolder,
    public: setiDefinitions.publicFolder,
    assets: setiDefinitions.assetsFolder,
    images: setiDefinitions.assetsFolder,
    img: setiDefinitions.assetsFolder,
    styles: setiDefinitions.assetsFolder,
    test: setiDefinitions.testFolder,
    tests: setiDefinitions.testFolder,
    __tests__: setiDefinitions.testFolder,
    node_modules: setiDefinitions.nodeModulesFolder,
    ".git": setiDefinitions.gitFolder,
    ".github": setiDefinitions.gitFolder,
    ".vscode": setiDefinitions.vscodeFolder,
  },

  folderExpandedNames: {
    src: setiDefinitions.srcFolderOpen,
    app: setiDefinitions.appFolderOpen,
    components: setiDefinitions.componentsFolderOpen,
    pages: setiDefinitions.componentsFolderOpen,
    public: setiDefinitions.publicFolderOpen,
    assets: setiDefinitions.assetsFolderOpen,
    images: setiDefinitions.assetsFolderOpen,
    img: setiDefinitions.assetsFolderOpen,
    styles: setiDefinitions.assetsFolderOpen,
    test: setiDefinitions.testFolderOpen,
    tests: setiDefinitions.testFolderOpen,
    __tests__: setiDefinitions.testFolderOpen,
    node_modules: setiDefinitions.nodeModulesFolderOpen,
    ".git": setiDefinitions.gitFolderOpen,
    ".github": setiDefinitions.gitFolderOpen,
    ".vscode": setiDefinitions.vscodeFolderOpen,
  },
};

