import React from "react";
import { IconTheme, IconDefinition, IconRenderProps } from "../types";
import {
  SiJavascript, SiJavascriptHex,
  SiTypescript, SiTypescriptHex,
  SiReact, SiReactHex,
  SiHtml5, SiHtml5Hex,
  SiCss,
  SiSass, SiSassHex,
  SiLess, SiLessHex,
  SiVuedotjs, SiVuedotjsHex,
  SiSvelte, SiSvelteHex,
  SiAstro, SiAstroHex,
  SiPython, SiPythonHex,
  SiOpenjdk,
  SiC, SiCHex,
  SiCplusplus, SiCplusplusHex,
  SiDotnet, SiDotnetHex,
  SiGo, SiGoHex,
  SiRust,
  SiPhp, SiPhpHex,
  SiRuby, SiRubyHex,
  SiSwift, SiSwiftHex,
  SiKotlin, SiKotlinHex,
  SiDart, SiDartHex,
  SiJson,
  SiYaml, SiYamlHex,
  SiToml, SiTomlHex,
  SiXml, SiXmlHex,
  SiDotenv, SiDotenvHex,
  SiMarkdown,
  SiMdx, SiMdxHex,
  SiPostgresql, SiPostgresqlHex,
  SiMysql, SiMysqlHex,
  SiSqlite, SiSqliteHex,
  SiPrisma, SiPrismaHex,
  SiGraphql, SiGraphqlHex,
  SiGnubash, SiGnubashHex,
  SiZsh, SiZshHex,
  SiFishshell, SiFishshellHex,
  SiDocker, SiDockerHex,
  SiGit, SiGitHex,
  SiNpm, SiNpmHex,
  SiPnpm, SiPnpmHex,
  SiYarn, SiYarnHex,
  SiBun,
  SiVite, SiViteHex,
  SiNextdotjs,
  SiTailwindcss, SiTailwindcssHex,
  SiPostcss, SiPostcssHex,
  SiEslint, SiEslintHex,
  SiPrettier, SiPrettierHex,
  SiVitest, SiVitestHex,
  SiJest, SiJestHex,
  SiCypress, SiCypressHex,
  SiWebpack, SiWebpackHex,
  SiBabel, SiBabelHex,
  SiRollupdotjs, SiRollupdotjsHex,
  SiTurborepo, SiTurborepoHex,
  SiTauri, SiTauriHex,
  SiCmake, SiCmakeHex,
  SiGnu, SiGnuHex,
  SiOpensourceinitiative, SiOpensourceinitiativeHex,
  SiSvg, SiSvgHex,
  SiJpeg, SiJpegHex,
  Si7zip,
  type IconType,
} from "@icons-pack/react-simple-icons";
import {
  DefaultFileIcon,
  FolderClosedIcon,
  FolderOpenIcon,
  SrcFolderClosed,
  SrcFolderOpen,
  ComponentsFolderClosed,
  ComponentsFolderOpen,
  AppFolderClosed,
  AppFolderOpen,
  PublicFolderClosed,
  PublicFolderOpen,
  AssetsFolderClosed,
  AssetsFolderOpen,
  TestFolderClosed,
  TestFolderOpen,
  NodeModulesFolderClosed,
  NodeModulesFolderOpen,
  GitFolderClosed,
  GitFolderOpen,
  VscodeFolderClosed,
  VscodeFolderOpen,
} from "../components/folder-svgs";

function makeSimpleIcon(
  id: string,
  name: string,
  IconComponent: IconType,
  brandColor?: string
): IconDefinition {
  return {
    id,
    name,
    color: brandColor,
    render: (props: IconRenderProps) =>
      React.createElement(IconComponent, {
        color: brandColor ?? "default",
        size: "100%",
        className: props.className,
        title: props.title,
        style: props.style,
        role: props.title ? "img" : "presentation",
        "aria-hidden": !props.title,
      }),
  };
}

export const simpleIconsDefinitions: Record<string, IconDefinition> = {
  // Programming Languages & Frameworks
  typescript: makeSimpleIcon("simple-icons-typescript", "TypeScript", SiTypescript, SiTypescriptHex),
  reactTs: makeSimpleIcon("simple-icons-react-ts", "React TypeScript", SiReact, SiReactHex),
  javascript: makeSimpleIcon("simple-icons-javascript", "JavaScript", SiJavascript, SiJavascriptHex),
  reactJs: makeSimpleIcon("simple-icons-react-js", "React JavaScript", SiReact, SiReactHex),
  python: makeSimpleIcon("simple-icons-python", "Python", SiPython, SiPythonHex),
  rust: makeSimpleIcon("simple-icons-rust", "Rust", SiRust, "#DEA584"),
  go: makeSimpleIcon("simple-icons-go", "Go", SiGo, SiGoHex),
  java: makeSimpleIcon("simple-icons-java", "Java", SiOpenjdk, "#ED8B00"),
  cpp: makeSimpleIcon("simple-icons-cpp", "C++", SiCplusplus, SiCplusplusHex),
  c: makeSimpleIcon("simple-icons-c", "C", SiC, SiCHex),
  csharp: makeSimpleIcon("simple-icons-csharp", "C#", SiDotnet, SiDotnetHex),
  php: makeSimpleIcon("simple-icons-php", "PHP", SiPhp, SiPhpHex),
  ruby: makeSimpleIcon("simple-icons-ruby", "Ruby", SiRuby, SiRubyHex),
  swift: makeSimpleIcon("simple-icons-swift", "Swift", SiSwift, SiSwiftHex),
  kotlin: makeSimpleIcon("simple-icons-kotlin", "Kotlin", SiKotlin, SiKotlinHex),
  dart: makeSimpleIcon("simple-icons-dart", "Dart", SiDart, SiDartHex),
  vue: makeSimpleIcon("simple-icons-vue", "Vue.js", SiVuedotjs, SiVuedotjsHex),
  svelte: makeSimpleIcon("simple-icons-svelte", "Svelte", SiSvelte, SiSvelteHex),
  astro: makeSimpleIcon("simple-icons-astro", "Astro", SiAstro, SiAstroHex),

  // Web & Styles
  html: makeSimpleIcon("simple-icons-html", "HTML", SiHtml5, SiHtml5Hex),
  css: makeSimpleIcon("simple-icons-css", "CSS", SiCss, "#1572B6"),
  sass: makeSimpleIcon("simple-icons-sass", "Sass", SiSass, SiSassHex),
  less: makeSimpleIcon("simple-icons-less", "Less", SiLess, SiLessHex),
  tailwind: makeSimpleIcon("simple-icons-tailwind", "Tailwind CSS", SiTailwindcss, SiTailwindcssHex),
  postcss: makeSimpleIcon("simple-icons-postcss", "PostCSS", SiPostcss, SiPostcssHex),

  // Data & Config
  json: makeSimpleIcon("simple-icons-json", "JSON", SiJson, "#CBCB41"),
  yaml: makeSimpleIcon("simple-icons-yaml", "YAML", SiYaml, SiYamlHex),
  toml: makeSimpleIcon("simple-icons-toml", "TOML", SiToml, SiTomlHex),
  xml: makeSimpleIcon("simple-icons-xml", "XML", SiXml, SiXmlHex),
  env: makeSimpleIcon("simple-icons-env", "Environment", SiDotenv, SiDotenvHex),

  // Documentation
  markdown: makeSimpleIcon("simple-icons-markdown", "Markdown", SiMarkdown, "#519ABA"),
  mdx: makeSimpleIcon("simple-icons-mdx", "MDX", SiMdx, SiMdxHex),

  // Databases
  sql: makeSimpleIcon("simple-icons-sql", "SQL", SiPostgresql, SiPostgresqlHex),
  mysql: makeSimpleIcon("simple-icons-mysql", "MySQL", SiMysql, SiMysqlHex),
  sqlite: makeSimpleIcon("simple-icons-sqlite", "SQLite", SiSqlite, SiSqliteHex),
  prisma: makeSimpleIcon("simple-icons-prisma", "Prisma", SiPrisma, SiPrismaHex),
  graphql: makeSimpleIcon("simple-icons-graphql", "GraphQL", SiGraphql, SiGraphqlHex),

  // Shell & Scripts
  shell: makeSimpleIcon("simple-icons-shell", "Shell", SiGnubash, SiGnubashHex),
  zsh: makeSimpleIcon("simple-icons-zsh", "Zsh", SiZsh, SiZshHex),
  fish: makeSimpleIcon("simple-icons-fish", "Fish", SiFishshell, SiFishshellHex),

  // Tools & Build Systems
  git: makeSimpleIcon("simple-icons-git", "Git", SiGit, SiGitHex),
  docker: makeSimpleIcon("simple-icons-docker", "Docker", SiDocker, SiDockerHex),
  npm: makeSimpleIcon("simple-icons-npm", "NPM", SiNpm, SiNpmHex),
  yarn: makeSimpleIcon("simple-icons-yarn", "Yarn", SiYarn, SiYarnHex),
  pnpm: makeSimpleIcon("simple-icons-pnpm", "PNPM", SiPnpm, SiPnpmHex),
  bun: makeSimpleIcon("simple-icons-bun", "Bun", SiBun, "#FBF0DF"),
  vite: makeSimpleIcon("simple-icons-vite", "Vite", SiVite, SiViteHex),
  nextjs: makeSimpleIcon("simple-icons-nextjs", "Next.js", SiNextdotjs, "currentColor"),
  eslint: makeSimpleIcon("simple-icons-eslint", "ESLint", SiEslint, SiEslintHex),
  prettier: makeSimpleIcon("simple-icons-prettier", "Prettier", SiPrettier, SiPrettierHex),
  vitest: makeSimpleIcon("simple-icons-vitest", "Vitest", SiVitest, SiVitestHex),
  jest: makeSimpleIcon("simple-icons-jest", "Jest", SiJest, SiJestHex),
  cypress: makeSimpleIcon("simple-icons-cypress", "Cypress", SiCypress, SiCypressHex),
  webpack: makeSimpleIcon("simple-icons-webpack", "Webpack", SiWebpack, SiWebpackHex),
  babel: makeSimpleIcon("simple-icons-babel", "Babel", SiBabel, SiBabelHex),
  rollup: makeSimpleIcon("simple-icons-rollup", "Rollup", SiRollupdotjs, SiRollupdotjsHex),
  turborepo: makeSimpleIcon("simple-icons-turborepo", "Turborepo", SiTurborepo, SiTurborepoHex),
  tauri: makeSimpleIcon("simple-icons-tauri", "Tauri", SiTauri, SiTauriHex),
  cmake: makeSimpleIcon("simple-icons-cmake", "CMake", SiCmake, SiCmakeHex),
  makefile: makeSimpleIcon("simple-icons-makefile", "Makefile", SiGnu, SiGnuHex),
  license: makeSimpleIcon("simple-icons-license", "License", SiOpensourceinitiative, SiOpensourceinitiativeHex),

  // Media & Archives
  svg: makeSimpleIcon("simple-icons-svg", "SVG", SiSvg, SiSvgHex),
  image: makeSimpleIcon("simple-icons-image", "Image", SiJpeg, SiJpegHex),
  archive: makeSimpleIcon("simple-icons-archive", "Archive", Si7zip, "#CCA152"),

  // Fallbacks & Defaults
  defaultFile: { id: "default-file", name: "File", render: DefaultFileIcon, color: "#8A8A8A" },
  defaultFolder: { id: "default-folder", name: "Folder", render: FolderClosedIcon, color: "#38bdf8" },
  defaultFolderExpanded: { id: "default-folder-expanded", name: "Folder (Open)", render: FolderOpenIcon, color: "#38bdf8" },

  // Specialized Folders (macOS Style)
  srcFolder: { id: "folder-src", name: "Source Folder", render: SrcFolderClosed, color: "#38bdf8" },
  srcFolderOpen: { id: "folder-src-open", name: "Source Folder (Open)", render: SrcFolderOpen, color: "#38bdf8" },
  componentsFolder: { id: "folder-components", name: "Components Folder", render: ComponentsFolderClosed, color: "#38bdf8" },
  componentsFolderOpen: { id: "folder-components-open", name: "Components Folder (Open)", render: ComponentsFolderOpen, color: "#38bdf8" },
  appFolder: { id: "folder-app", name: "App Folder", render: AppFolderClosed, color: "#38bdf8" },
  appFolderOpen: { id: "folder-app-open", name: "App Folder (Open)", render: AppFolderOpen, color: "#38bdf8" },
  publicFolder: { id: "folder-public", name: "Public Folder", render: PublicFolderClosed, color: "#38bdf8" },
  publicFolderOpen: { id: "folder-public-open", name: "Public Folder (Open)", render: PublicFolderOpen, color: "#38bdf8" },
  assetsFolder: { id: "folder-assets", name: "Assets Folder", render: AssetsFolderClosed, color: "#38bdf8" },
  assetsFolderOpen: { id: "folder-assets-open", name: "Assets Folder (Open)", render: AssetsFolderOpen, color: "#38bdf8" },
  testFolder: { id: "folder-test", name: "Test Folder", render: TestFolderClosed, color: "#38bdf8" },
  testFolderOpen: { id: "folder-test-open", name: "Test Folder (Open)", render: TestFolderOpen, color: "#38bdf8" },
  nodeModulesFolder: { id: "folder-node-modules", name: "Node Modules Folder", render: NodeModulesFolderClosed, color: "#38bdf8" },
  nodeModulesFolderOpen: { id: "folder-node-modules-open", name: "Node Modules Folder (Open)", render: NodeModulesFolderOpen, color: "#38bdf8" },
  gitFolder: { id: "folder-git", name: "Git Folder", render: GitFolderClosed, color: "#38bdf8" },
  gitFolderOpen: { id: "folder-git-open", name: "Git Folder (Open)", render: GitFolderOpen, color: "#38bdf8" },
  vscodeFolder: { id: "folder-vscode", name: "VS Code Folder", render: VscodeFolderClosed, color: "#38bdf8" },
  vscodeFolderOpen: { id: "folder-vscode-open", name: "VS Code Folder (Open)", render: VscodeFolderOpen, color: "#38bdf8" },
};

export const simpleIconsTheme: IconTheme = {
  id: "simple-icons",
  name: "Simple Icons",
  defaultFile: simpleIconsDefinitions.defaultFile,
  defaultFolder: simpleIconsDefinitions.defaultFolder,
  defaultFolderExpanded: simpleIconsDefinitions.defaultFolderExpanded,

  exactFiles: {
    // Node / Package managers
    "package.json": simpleIconsDefinitions.npm,
    "package-lock.json": simpleIconsDefinitions.npm,
    ".npmrc": simpleIconsDefinitions.npm,
    "yarn.lock": simpleIconsDefinitions.yarn,
    ".yarnrc": simpleIconsDefinitions.yarn,
    ".yarnrc.yml": simpleIconsDefinitions.yarn,
    "pnpm-lock.yaml": simpleIconsDefinitions.pnpm,
    "pnpm-workspace.yaml": simpleIconsDefinitions.pnpm,
    ".pnpmfile.cjs": simpleIconsDefinitions.pnpm,
    "bun.lockb": simpleIconsDefinitions.bun,
    "bun.lock": simpleIconsDefinitions.bun,
    "bunfig.toml": simpleIconsDefinitions.bun,

    // TypeScript / JavaScript config
    "tsconfig.json": simpleIconsDefinitions.typescript,
    "tsconfig.app.json": simpleIconsDefinitions.typescript,
    "tsconfig.node.json": simpleIconsDefinitions.typescript,
    "jsconfig.json": simpleIconsDefinitions.javascript,

    // Bundlers / Frameworks
    "vite.config.ts": simpleIconsDefinitions.vite,
    "vite.config.js": simpleIconsDefinitions.vite,
    "vite.config.mjs": simpleIconsDefinitions.vite,
    "vite.config.cjs": simpleIconsDefinitions.vite,
    "next.config.js": simpleIconsDefinitions.nextjs,
    "next.config.mjs": simpleIconsDefinitions.nextjs,
    "next.config.ts": simpleIconsDefinitions.nextjs,
    "next.config.cjs": simpleIconsDefinitions.nextjs,
    "tailwind.config.js": simpleIconsDefinitions.tailwind,
    "tailwind.config.ts": simpleIconsDefinitions.tailwind,
    "tailwind.config.cjs": simpleIconsDefinitions.tailwind,
    "tailwind.config.mjs": simpleIconsDefinitions.tailwind,
    "postcss.config.js": simpleIconsDefinitions.postcss,
    "postcss.config.mjs": simpleIconsDefinitions.postcss,
    "postcss.config.cjs": simpleIconsDefinitions.postcss,
    "postcss.config.ts": simpleIconsDefinitions.postcss,

    // Linters & Formatters & Testers
    "eslint.config.js": simpleIconsDefinitions.eslint,
    "eslint.config.mjs": simpleIconsDefinitions.eslint,
    "eslint.config.cjs": simpleIconsDefinitions.eslint,
    "eslint.config.ts": simpleIconsDefinitions.eslint,
    ".eslintrc": simpleIconsDefinitions.eslint,
    ".eslintrc.json": simpleIconsDefinitions.eslint,
    ".eslintrc.js": simpleIconsDefinitions.eslint,
    ".eslintrc.cjs": simpleIconsDefinitions.eslint,
    ".eslintignore": simpleIconsDefinitions.eslint,
    ".prettierrc": simpleIconsDefinitions.prettier,
    ".prettierrc.json": simpleIconsDefinitions.prettier,
    ".prettierrc.js": simpleIconsDefinitions.prettier,
    ".prettierrc.cjs": simpleIconsDefinitions.prettier,
    ".prettierrc.yml": simpleIconsDefinitions.prettier,
    ".prettierrc.yaml": simpleIconsDefinitions.prettier,
    ".prettierignore": simpleIconsDefinitions.prettier,
    "vitest.config.ts": simpleIconsDefinitions.vitest,
    "vitest.config.js": simpleIconsDefinitions.vitest,
    "vitest.config.mjs": simpleIconsDefinitions.vitest,
    "jest.config.js": simpleIconsDefinitions.jest,
    "jest.config.ts": simpleIconsDefinitions.jest,
    "jest.config.mjs": simpleIconsDefinitions.jest,
    "cypress.config.ts": simpleIconsDefinitions.cypress,
    "cypress.config.js": simpleIconsDefinitions.cypress,
    "turbo.json": simpleIconsDefinitions.turborepo,
    "webpack.config.js": simpleIconsDefinitions.webpack,
    "webpack.config.ts": simpleIconsDefinitions.webpack,
    "babel.config.json": simpleIconsDefinitions.babel,
    "babel.config.js": simpleIconsDefinitions.babel,
    ".babelrc": simpleIconsDefinitions.babel,
    "rollup.config.js": simpleIconsDefinitions.rollup,
    "rollup.config.ts": simpleIconsDefinitions.rollup,
    "rollup.config.mjs": simpleIconsDefinitions.rollup,

    // Git
    ".gitignore": simpleIconsDefinitions.git,
    ".gitattributes": simpleIconsDefinitions.git,
    ".gitmodules": simpleIconsDefinitions.git,

    // Environment
    ".env": simpleIconsDefinitions.env,
    ".env.local": simpleIconsDefinitions.env,
    ".env.development": simpleIconsDefinitions.env,
    ".env.production": simpleIconsDefinitions.env,
    ".env.test": simpleIconsDefinitions.env,
    ".env.example": simpleIconsDefinitions.env,
    ".env.staging": simpleIconsDefinitions.env,

    // Containers & Deployments
    dockerfile: simpleIconsDefinitions.docker,
    "dockerfile.dev": simpleIconsDefinitions.docker,
    "dockerfile.prod": simpleIconsDefinitions.docker,
    "docker-compose.yml": simpleIconsDefinitions.docker,
    "docker-compose.yaml": simpleIconsDefinitions.docker,
    ".dockerignore": simpleIconsDefinitions.docker,

    // Build tools
    makefile: simpleIconsDefinitions.makefile,
    gnumakefile: simpleIconsDefinitions.makefile,
    "cmakelists.txt": simpleIconsDefinitions.cmake,

    // Documentation & Legal
    "readme.md": simpleIconsDefinitions.markdown,
    readme: simpleIconsDefinitions.markdown,
    license: simpleIconsDefinitions.license,
    "license.md": simpleIconsDefinitions.license,
    "license.txt": simpleIconsDefinitions.license,
    licence: simpleIconsDefinitions.license,

    // Rust & Tauri
    "cargo.toml": simpleIconsDefinitions.rust,
    "cargo.lock": simpleIconsDefinitions.rust,
    "tauri.conf.json": simpleIconsDefinitions.tauri,
  },

  filePatterns: [
    { id: "env-pattern", pattern: /^\.env(\..+)?$/i, icon: simpleIconsDefinitions.env },
    { id: "docker-pattern", pattern: /^dockerfile(\..+)?$/i, icon: simpleIconsDefinitions.docker },
    { id: "docker-compose-pattern", pattern: /^docker-compose(\..+)?\.ya?ml$/i, icon: simpleIconsDefinitions.docker },
    { id: "license-pattern", pattern: /^licen[sc]e(\..+)?$/i, icon: simpleIconsDefinitions.license },
    { id: "readme-pattern", pattern: /^readme(\..+)?$/i, icon: simpleIconsDefinitions.markdown },
    { id: "makefile-pattern", pattern: /^makefile(\..+)?$/i, icon: simpleIconsDefinitions.makefile },
    { id: "cmake-pattern", pattern: /^cmakelists(\..+)?$/i, icon: simpleIconsDefinitions.cmake },
  ],

  fileExtensions: {
    // TypeScript & React
    ts: simpleIconsDefinitions.typescript,
    cts: simpleIconsDefinitions.typescript,
    mts: simpleIconsDefinitions.typescript,
    tsx: simpleIconsDefinitions.reactTs,
    "d.ts": simpleIconsDefinitions.typescript,
    "d.mts": simpleIconsDefinitions.typescript,
    "d.cts": simpleIconsDefinitions.typescript,

    // JavaScript & React
    js: simpleIconsDefinitions.javascript,
    cjs: simpleIconsDefinitions.javascript,
    mjs: simpleIconsDefinitions.javascript,
    jsx: simpleIconsDefinitions.reactJs,

    // Programming Languages
    py: simpleIconsDefinitions.python,
    pyw: simpleIconsDefinitions.python,
    pyx: simpleIconsDefinitions.python,
    rs: simpleIconsDefinitions.rust,
    go: simpleIconsDefinitions.go,
    java: simpleIconsDefinitions.java,
    jar: simpleIconsDefinitions.java,
    class: simpleIconsDefinitions.java,
    c: simpleIconsDefinitions.c,
    h: simpleIconsDefinitions.c,
    cpp: simpleIconsDefinitions.cpp,
    cc: simpleIconsDefinitions.cpp,
    cxx: simpleIconsDefinitions.cpp,
    hpp: simpleIconsDefinitions.cpp,
    hxx: simpleIconsDefinitions.cpp,
    hh: simpleIconsDefinitions.cpp,
    cs: simpleIconsDefinitions.csharp,
    csx: simpleIconsDefinitions.csharp,
    php: simpleIconsDefinitions.php,
    phtml: simpleIconsDefinitions.php,
    rb: simpleIconsDefinitions.ruby,
    erb: simpleIconsDefinitions.ruby,
    swift: simpleIconsDefinitions.swift,
    kt: simpleIconsDefinitions.kotlin,
    kts: simpleIconsDefinitions.kotlin,
    dart: simpleIconsDefinitions.dart,

    // Frameworks
    vue: simpleIconsDefinitions.vue,
    svelte: simpleIconsDefinitions.svelte,
    astro: simpleIconsDefinitions.astro,

    // Web & Styles
    html: simpleIconsDefinitions.html,
    htm: simpleIconsDefinitions.html,
    xhtml: simpleIconsDefinitions.html,
    css: simpleIconsDefinitions.css,
    scss: simpleIconsDefinitions.sass,
    sass: simpleIconsDefinitions.sass,
    less: simpleIconsDefinitions.less,

    // Data & Config formats
    json: simpleIconsDefinitions.json,
    json5: simpleIconsDefinitions.json,
    jsonc: simpleIconsDefinitions.json,
    yaml: simpleIconsDefinitions.yaml,
    yml: simpleIconsDefinitions.yaml,
    toml: simpleIconsDefinitions.toml,
    xml: simpleIconsDefinitions.xml,
    env: simpleIconsDefinitions.env,

    // Documentation
    md: simpleIconsDefinitions.markdown,
    markdown: simpleIconsDefinitions.markdown,
    mdown: simpleIconsDefinitions.markdown,
    mkd: simpleIconsDefinitions.markdown,
    mdx: simpleIconsDefinitions.mdx,

    // Shell scripts & Database
    sh: simpleIconsDefinitions.shell,
    bash: simpleIconsDefinitions.shell,
    zsh: simpleIconsDefinitions.zsh,
    fish: simpleIconsDefinitions.fish,
    ps1: simpleIconsDefinitions.shell,
    psm1: simpleIconsDefinitions.shell,
    psd1: simpleIconsDefinitions.shell,
    bat: simpleIconsDefinitions.shell,
    cmd: simpleIconsDefinitions.shell,
    sql: simpleIconsDefinitions.sql,
    pgsql: simpleIconsDefinitions.sql,
    mysql: simpleIconsDefinitions.mysql,
    sqlite: simpleIconsDefinitions.sqlite,
    prisma: simpleIconsDefinitions.prisma,
    graphql: simpleIconsDefinitions.graphql,
    gql: simpleIconsDefinitions.graphql,

    // Media
    svg: simpleIconsDefinitions.svg,
    png: simpleIconsDefinitions.image,
    jpg: simpleIconsDefinitions.image,
    jpeg: simpleIconsDefinitions.image,
    gif: simpleIconsDefinitions.image,
    webp: simpleIconsDefinitions.image,
    ico: simpleIconsDefinitions.image,
    bmp: simpleIconsDefinitions.image,
    tiff: simpleIconsDefinitions.image,

    // Archives
    zip: simpleIconsDefinitions.archive,
    tar: simpleIconsDefinitions.archive,
    gz: simpleIconsDefinitions.archive,
    "7z": simpleIconsDefinitions.archive,
    rar: simpleIconsDefinitions.archive,
    bz2: simpleIconsDefinitions.archive,
    "tar.gz": simpleIconsDefinitions.archive,
    "tar.bz2": simpleIconsDefinitions.archive,
    "tar.xz": simpleIconsDefinitions.archive,

    // Special
    dockerfile: simpleIconsDefinitions.docker,
    gitignore: simpleIconsDefinitions.git,
  },

  folderNames: {
    src: simpleIconsDefinitions.srcFolder,
    app: simpleIconsDefinitions.appFolder,
    components: simpleIconsDefinitions.componentsFolder,
    pages: simpleIconsDefinitions.componentsFolder,
    public: simpleIconsDefinitions.publicFolder,
    assets: simpleIconsDefinitions.assetsFolder,
    images: simpleIconsDefinitions.assetsFolder,
    img: simpleIconsDefinitions.assetsFolder,
    styles: simpleIconsDefinitions.assetsFolder,
    test: simpleIconsDefinitions.testFolder,
    tests: simpleIconsDefinitions.testFolder,
    __tests__: simpleIconsDefinitions.testFolder,
    node_modules: simpleIconsDefinitions.nodeModulesFolder,
    ".git": simpleIconsDefinitions.gitFolder,
    ".github": simpleIconsDefinitions.gitFolder,
    ".vscode": simpleIconsDefinitions.vscodeFolder,
  },

  folderExpandedNames: {
    src: simpleIconsDefinitions.srcFolderOpen,
    app: simpleIconsDefinitions.appFolderOpen,
    components: simpleIconsDefinitions.componentsFolderOpen,
    pages: simpleIconsDefinitions.componentsFolderOpen,
    public: simpleIconsDefinitions.publicFolderOpen,
    assets: simpleIconsDefinitions.assetsFolderOpen,
    images: simpleIconsDefinitions.assetsFolderOpen,
    img: simpleIconsDefinitions.assetsFolderOpen,
    styles: simpleIconsDefinitions.assetsFolderOpen,
    test: simpleIconsDefinitions.testFolderOpen,
    tests: simpleIconsDefinitions.testFolderOpen,
    __tests__: simpleIconsDefinitions.testFolderOpen,
    node_modules: simpleIconsDefinitions.nodeModulesFolderOpen,
    ".git": simpleIconsDefinitions.gitFolderOpen,
    ".github": simpleIconsDefinitions.gitFolderOpen,
    ".vscode": simpleIconsDefinitions.vscodeFolderOpen,
  },
};
